// Code generated by ent, DO NOT EDIT.

package account

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldInitialBalance holds the string denoting the initial_balance field in the database.
	FieldInitialBalance = "initial_balance"
	// FieldCreditLimit holds the string denoting the credit_limit field in the database.
	FieldCreditLimit = "credit_limit"
	// FieldBillDay holds the string denoting the bill_day field in the database.
	FieldBillDay = "bill_day"
	// FieldApr holds the string denoting the apr field in the database.
	FieldApr = "apr"
	// FieldCurrencyCode holds the string denoting the currency_code field in the database.
	FieldCurrencyCode = "currency_code"
	// FieldNo holds the string denoting the no field in the database.
	FieldNo = "no"
	// FieldInclude holds the string denoting the include field in the database.
	FieldInclude = "include"
	// FieldCanExpense holds the string denoting the can_expense field in the database.
	FieldCanExpense = "can_expense"
	// FieldCanIncome holds the string denoting the can_income field in the database.
	FieldCanIncome = "can_income"
	// FieldCanTransferFrom holds the string denoting the can_transfer_from field in the database.
	FieldCanTransferFrom = "can_transfer_from"
	// FieldCanTransferTo holds the string denoting the can_transfer_to field in the database.
	FieldCanTransferTo = "can_transfer_to"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldEnable holds the string denoting the enable field in the database.
	FieldEnable = "enable"
	// Table holds the table name of the account in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldSortOrder,
	FieldName,
	FieldType,
	FieldBalance,
	FieldInitialBalance,
	FieldCreditLimit,
	FieldBillDay,
	FieldApr,
	FieldCurrencyCode,
	FieldNo,
	FieldInclude,
	FieldCanExpense,
	FieldCanIncome,
	FieldCanTransferFrom,
	FieldCanTransferTo,
	FieldNotes,
	FieldEnable,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-cms/app/core/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder uint32
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance float64
	// DefaultInitialBalance holds the default value on creation for the "initial_balance" field.
	DefaultInitialBalance float64
	// DefaultCreditLimit holds the default value on creation for the "credit_limit" field.
	DefaultCreditLimit float64
	// CurrencyCodeValidator is a validator for the "currency_code" field. It is called by the builders before save.
	CurrencyCodeValidator func(string) error
	// NoValidator is a validator for the "no" field. It is called by the builders before save.
	NoValidator func(string) error
	// DefaultInclude holds the default value on creation for the "include" field.
	DefaultInclude bool
	// DefaultCanExpense holds the default value on creation for the "can_expense" field.
	DefaultCanExpense bool
	// DefaultCanIncome holds the default value on creation for the "can_income" field.
	DefaultCanIncome bool
	// DefaultCanTransferFrom holds the default value on creation for the "can_transfer_from" field.
	DefaultCanTransferFrom bool
	// DefaultCanTransferTo holds the default value on creation for the "can_transfer_to" field.
	DefaultCanTransferTo bool
	// NotesValidator is a validator for the "notes" field. It is called by the builders before save.
	NotesValidator func(string) error
	// DefaultEnable holds the default value on creation for the "enable" field.
	DefaultEnable bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeAccountTypeChecking Type = "ACCOUNT_TYPE_CHECKING"
	TypeAccountTypeCredit   Type = "ACCOUNT_TYPE_CREDIT"
	TypeAccountTypeAsset    Type = "ACCOUNT_TYPE_ASSET"
	TypeAccountTypeDebt     Type = "ACCOUNT_TYPE_DEBT"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeAccountTypeChecking, TypeAccountTypeCredit, TypeAccountTypeAsset, TypeAccountTypeDebt:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByInitialBalance orders the results by the initial_balance field.
func ByInitialBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitialBalance, opts...).ToFunc()
}

// ByCreditLimit orders the results by the credit_limit field.
func ByCreditLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditLimit, opts...).ToFunc()
}

// ByBillDay orders the results by the bill_day field.
func ByBillDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillDay, opts...).ToFunc()
}

// ByApr orders the results by the apr field.
func ByApr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApr, opts...).ToFunc()
}

// ByCurrencyCode orders the results by the currency_code field.
func ByCurrencyCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyCode, opts...).ToFunc()
}

// ByNo orders the results by the no field.
func ByNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNo, opts...).ToFunc()
}

// ByInclude orders the results by the include field.
func ByInclude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInclude, opts...).ToFunc()
}

// ByCanExpense orders the results by the can_expense field.
func ByCanExpense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanExpense, opts...).ToFunc()
}

// ByCanIncome orders the results by the can_income field.
func ByCanIncome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanIncome, opts...).ToFunc()
}

// ByCanTransferFrom orders the results by the can_transfer_from field.
func ByCanTransferFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanTransferFrom, opts...).ToFunc()
}

// ByCanTransferTo orders the results by the can_transfer_to field.
func ByCanTransferTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanTransferTo, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByEnable orders the results by the enable field.
func ByEnable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnable, opts...).ToFunc()
}
