// Code generated by ent, DO NOT EDIT.

package flowfile

import (
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldDeletedAt, v))
}

// FlowID applies equality check predicate on the "flow_id" field. It's identical to FlowIDEQ.
func FlowID(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldFlowID, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldCreatorID, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldCreateTime, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldContentType, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldSize, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldOriginalName, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldObjectKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldDeletedAt))
}

// FlowIDEQ applies the EQ predicate on the "flow_id" field.
func FlowIDEQ(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldFlowID, v))
}

// FlowIDNEQ applies the NEQ predicate on the "flow_id" field.
func FlowIDNEQ(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldFlowID, v))
}

// FlowIDIn applies the In predicate on the "flow_id" field.
func FlowIDIn(vs ...uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldFlowID, vs...))
}

// FlowIDNotIn applies the NotIn predicate on the "flow_id" field.
func FlowIDNotIn(vs ...uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldFlowID, vs...))
}

// FlowIDGT applies the GT predicate on the "flow_id" field.
func FlowIDGT(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldFlowID, v))
}

// FlowIDGTE applies the GTE predicate on the "flow_id" field.
func FlowIDGTE(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldFlowID, v))
}

// FlowIDLT applies the LT predicate on the "flow_id" field.
func FlowIDLT(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldFlowID, v))
}

// FlowIDLTE applies the LTE predicate on the "flow_id" field.
func FlowIDLTE(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldFlowID, v))
}

// FlowIDIsNil applies the IsNil predicate on the "flow_id" field.
func FlowIDIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldFlowID))
}

// FlowIDNotNil applies the NotNil predicate on the "flow_id" field.
func FlowIDNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldFlowID))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldCreatorID, vs...))
}

// CreatorIDGT applies the GT predicate on the "creator_id" field.
func CreatorIDGT(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldCreatorID, v))
}

// CreatorIDGTE applies the GTE predicate on the "creator_id" field.
func CreatorIDGTE(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldCreatorID, v))
}

// CreatorIDLT applies the LT predicate on the "creator_id" field.
func CreatorIDLT(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldCreatorID, v))
}

// CreatorIDLTE applies the LTE predicate on the "creator_id" field.
func CreatorIDLTE(v uint32) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldCreatorID, v))
}

// CreatorIDIsNil applies the IsNil predicate on the "creator_id" field.
func CreatorIDIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldCreatorID))
}

// CreatorIDNotNil applies the NotNil predicate on the "creator_id" field.
func CreatorIDNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldCreatorID))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldCreateTime))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeIsNil applies the IsNil predicate on the "content_type" field.
func ContentTypeIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldContentType))
}

// ContentTypeNotNil applies the NotNil predicate on the "content_type" field.
func ContentTypeNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldContentType))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldContainsFold(FieldContentType, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldSize))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameIsNil applies the IsNil predicate on the "original_name" field.
func OriginalNameIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldOriginalName))
}

// OriginalNameNotNil applies the NotNil predicate on the "original_name" field.
func OriginalNameNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldOriginalName))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldContainsFold(FieldOriginalName, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyIsNil applies the IsNil predicate on the "object_key" field.
func ObjectKeyIsNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldIsNull(FieldObjectKey))
}

// ObjectKeyNotNil applies the NotNil predicate on the "object_key" field.
func ObjectKeyNotNil() predicate.FlowFile {
	return predicate.FlowFile(sql.FieldNotNull(FieldObjectKey))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.FlowFile {
	return predicate.FlowFile(sql.FieldContainsFold(FieldObjectKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlowFile) predicate.FlowFile {
	return predicate.FlowFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlowFile) predicate.FlowFile {
	return predicate.FlowFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlowFile) predicate.FlowFile {
	return predicate.FlowFile(sql.NotPredicates(p))
}
