// Code generated by ent, DO NOT EDIT.

package rolemetadata

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rolemetadata type in the database.
	Label = "role_metadata"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldTemplateFor holds the string denoting the template_for field in the database.
	FieldTemplateFor = "template_for"
	// FieldTemplateVersion holds the string denoting the template_version field in the database.
	FieldTemplateVersion = "template_version"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastSyncedVersion holds the string denoting the last_synced_version field in the database.
	FieldLastSyncedVersion = "last_synced_version"
	// FieldIsTemplate holds the string denoting the is_template field in the database.
	FieldIsTemplate = "is_template"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// Table holds the table name of the rolemetadata in the database.
	Table = "sys_role_metadata"
)

// Columns holds all SQL columns for rolemetadata fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTenantID,
	FieldRoleID,
	FieldTemplateFor,
	FieldTemplateVersion,
	FieldLastSyncedAt,
	FieldLastSyncedVersion,
	FieldIsTemplate,
	FieldKey,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-cms/app/core/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// TemplateForValidator is a validator for the "template_for" field. It is called by the builders before save.
	TemplateForValidator func(string) error
	// DefaultTemplateVersion holds the default value on creation for the "template_version" field.
	DefaultTemplateVersion int32
	// DefaultLastSyncedVersion holds the default value on creation for the "last_synced_version" field.
	DefaultLastSyncedVersion int32
	// DefaultIsTemplate holds the default value on creation for the "is_template" field.
	DefaultIsTemplate bool
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// ValueValidator is a validator for the "value" field. It is called by the builders before save.
	ValueValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the RoleMetadata queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}

// ByTemplateFor orders the results by the template_for field.
func ByTemplateFor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateFor, opts...).ToFunc()
}

// ByTemplateVersion orders the results by the template_version field.
func ByTemplateVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateVersion, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastSyncedVersion orders the results by the last_synced_version field.
func ByLastSyncedVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedVersion, opts...).ToFunc()
}

// ByIsTemplate orders the results by the is_template field.
func ByIsTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsTemplate, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}
