// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/balanceflow"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BalanceFlowCreate is the builder for creating a BalanceFlow entity.
type BalanceFlowCreate struct {
	config
	mutation *BalanceFlowMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *BalanceFlowCreate) SetTenantID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableTenantID(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceFlowCreate) SetCreatedAt(v time.Time) *BalanceFlowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableCreatedAt(v *time.Time) *BalanceFlowCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BalanceFlowCreate) SetUpdatedAt(v time.Time) *BalanceFlowCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableUpdatedAt(v *time.Time) *BalanceFlowCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BalanceFlowCreate) SetDeletedAt(v time.Time) *BalanceFlowCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableDeletedAt(v *time.Time) *BalanceFlowCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *BalanceFlowCreate) SetCreatedBy(v uint32) *BalanceFlowCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableCreatedBy(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *BalanceFlowCreate) SetUpdatedBy(v uint32) *BalanceFlowCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableUpdatedBy(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *BalanceFlowCreate) SetDeletedBy(v uint32) *BalanceFlowCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableDeletedBy(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetBookID sets the "book_id" field.
func (_c *BalanceFlowCreate) SetBookID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetBookID(v)
	return _c
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableBookID(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetBookID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *BalanceFlowCreate) SetType(v balanceflow.Type) *BalanceFlowCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableType(v *balanceflow.Type) *BalanceFlowCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *BalanceFlowCreate) SetAmount(v float64) *BalanceFlowCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableAmount(v *float64) *BalanceFlowCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetConvertedAmount sets the "converted_amount" field.
func (_c *BalanceFlowCreate) SetConvertedAmount(v float64) *BalanceFlowCreate {
	_c.mutation.SetConvertedAmount(v)
	return _c
}

// SetNillableConvertedAmount sets the "converted_amount" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableConvertedAmount(v *float64) *BalanceFlowCreate {
	if v != nil {
		_c.SetConvertedAmount(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *BalanceFlowCreate) SetAccountID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableAccountID(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetToAccountID sets the "to_account_id" field.
func (_c *BalanceFlowCreate) SetToAccountID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetToAccountID(v)
	return _c
}

// SetNillableToAccountID sets the "to_account_id" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableToAccountID(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetToAccountID(*v)
	}
	return _c
}

// SetPayeeID sets the "payee_id" field.
func (_c *BalanceFlowCreate) SetPayeeID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetPayeeID(v)
	return _c
}

// SetNillablePayeeID sets the "payee_id" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillablePayeeID(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetPayeeID(*v)
	}
	return _c
}

// SetCreatorID sets the "creator_id" field.
func (_c *BalanceFlowCreate) SetCreatorID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetCreatorID(v)
	return _c
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableCreatorID(v *uint32) *BalanceFlowCreate {
	if v != nil {
		_c.SetCreatorID(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *BalanceFlowCreate) SetCreateTime(v int64) *BalanceFlowCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableCreateTime(v *int64) *BalanceFlowCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *BalanceFlowCreate) SetTitle(v string) *BalanceFlowCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableTitle(v *string) *BalanceFlowCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *BalanceFlowCreate) SetNotes(v string) *BalanceFlowCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableNotes(v *string) *BalanceFlowCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetConfirm sets the "confirm" field.
func (_c *BalanceFlowCreate) SetConfirm(v bool) *BalanceFlowCreate {
	_c.mutation.SetConfirm(v)
	return _c
}

// SetNillableConfirm sets the "confirm" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableConfirm(v *bool) *BalanceFlowCreate {
	if v != nil {
		_c.SetConfirm(*v)
	}
	return _c
}

// SetInclude sets the "include" field.
func (_c *BalanceFlowCreate) SetInclude(v bool) *BalanceFlowCreate {
	_c.mutation.SetInclude(v)
	return _c
}

// SetNillableInclude sets the "include" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableInclude(v *bool) *BalanceFlowCreate {
	if v != nil {
		_c.SetInclude(*v)
	}
	return _c
}

// SetInsertAt sets the "insert_at" field.
func (_c *BalanceFlowCreate) SetInsertAt(v int64) *BalanceFlowCreate {
	_c.mutation.SetInsertAt(v)
	return _c
}

// SetNillableInsertAt sets the "insert_at" field if the given value is not nil.
func (_c *BalanceFlowCreate) SetNillableInsertAt(v *int64) *BalanceFlowCreate {
	if v != nil {
		_c.SetInsertAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BalanceFlowCreate) SetID(v uint32) *BalanceFlowCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BalanceFlowMutation object of the builder.
func (_c *BalanceFlowCreate) Mutation() *BalanceFlowMutation {
	return _c.mutation
}

// Save creates the BalanceFlow in the database.
func (_c *BalanceFlowCreate) Save(ctx context.Context) (*BalanceFlow, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceFlowCreate) SaveX(ctx context.Context) *BalanceFlow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceFlowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceFlowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceFlowCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := balanceflow.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Confirm(); !ok {
		v := balanceflow.DefaultConfirm
		_c.mutation.SetConfirm(v)
	}
	if _, ok := _c.mutation.Include(); !ok {
		v := balanceflow.DefaultInclude
		_c.mutation.SetInclude(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceFlowCreate) check() error {
	if v, ok := _c.mutation.GetType(); ok {
		if err := balanceflow.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BalanceFlow.type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := balanceflow.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BalanceFlow.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Notes(); ok {
		if err := balanceflow.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "BalanceFlow.notes": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := balanceflow.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BalanceFlow.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BalanceFlowCreate) sqlSave(ctx context.Context) (*BalanceFlow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceFlowCreate) createSpec() (*BalanceFlow, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceFlow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balanceflow.Table, sqlgraph.NewFieldSpec(balanceflow.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(balanceflow.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balanceflow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(balanceflow.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(balanceflow.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(balanceflow.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(balanceflow.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(balanceflow.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.BookID(); ok {
		_spec.SetField(balanceflow.FieldBookID, field.TypeUint32, value)
		_node.BookID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(balanceflow.FieldType, field.TypeEnum, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(balanceflow.FieldAmount, field.TypeFloat64, value)
		_node.Amount = &value
	}
	if value, ok := _c.mutation.ConvertedAmount(); ok {
		_spec.SetField(balanceflow.FieldConvertedAmount, field.TypeFloat64, value)
		_node.ConvertedAmount = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(balanceflow.FieldAccountID, field.TypeUint32, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.ToAccountID(); ok {
		_spec.SetField(balanceflow.FieldToAccountID, field.TypeUint32, value)
		_node.ToAccountID = &value
	}
	if value, ok := _c.mutation.PayeeID(); ok {
		_spec.SetField(balanceflow.FieldPayeeID, field.TypeUint32, value)
		_node.PayeeID = &value
	}
	if value, ok := _c.mutation.CreatorID(); ok {
		_spec.SetField(balanceflow.FieldCreatorID, field.TypeUint32, value)
		_node.CreatorID = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(balanceflow.FieldCreateTime, field.TypeInt64, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(balanceflow.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(balanceflow.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Confirm(); ok {
		_spec.SetField(balanceflow.FieldConfirm, field.TypeBool, value)
		_node.Confirm = &value
	}
	if value, ok := _c.mutation.Include(); ok {
		_spec.SetField(balanceflow.FieldInclude, field.TypeBool, value)
		_node.Include = &value
	}
	if value, ok := _c.mutation.InsertAt(); ok {
		_spec.SetField(balanceflow.FieldInsertAt, field.TypeInt64, value)
		_node.InsertAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceFlow.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceFlowUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceFlowCreate) OnConflict(opts ...sql.ConflictOption) *BalanceFlowUpsertOne {
	_c.conflict = opts
	return &BalanceFlowUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceFlow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceFlowCreate) OnConflictColumns(columns ...string) *BalanceFlowUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceFlowUpsertOne{
		create: _c,
	}
}

type (
	// BalanceFlowUpsertOne is the builder for "upsert"-ing
	//  one BalanceFlow node.
	BalanceFlowUpsertOne struct {
		create *BalanceFlowCreate
	}

	// BalanceFlowUpsert is the "OnConflict" setter.
	BalanceFlowUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceFlowUpsert) SetUpdatedAt(v time.Time) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateUpdatedAt() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *BalanceFlowUpsert) ClearUpdatedAt() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BalanceFlowUpsert) SetDeletedAt(v time.Time) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateDeletedAt() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BalanceFlowUpsert) ClearDeletedAt() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *BalanceFlowUpsert) SetCreatedBy(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateCreatedBy() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *BalanceFlowUpsert) AddCreatedBy(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *BalanceFlowUpsert) ClearCreatedBy() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *BalanceFlowUpsert) SetUpdatedBy(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateUpdatedBy() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *BalanceFlowUpsert) AddUpdatedBy(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *BalanceFlowUpsert) ClearUpdatedBy() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *BalanceFlowUpsert) SetDeletedBy(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateDeletedBy() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *BalanceFlowUpsert) AddDeletedBy(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *BalanceFlowUpsert) ClearDeletedBy() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldDeletedBy)
	return u
}

// SetBookID sets the "book_id" field.
func (u *BalanceFlowUpsert) SetBookID(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldBookID, v)
	return u
}

// UpdateBookID sets the "book_id" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateBookID() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldBookID)
	return u
}

// AddBookID adds v to the "book_id" field.
func (u *BalanceFlowUpsert) AddBookID(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldBookID, v)
	return u
}

// ClearBookID clears the value of the "book_id" field.
func (u *BalanceFlowUpsert) ClearBookID() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldBookID)
	return u
}

// SetType sets the "type" field.
func (u *BalanceFlowUpsert) SetType(v balanceflow.Type) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateType() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldType)
	return u
}

// ClearType clears the value of the "type" field.
func (u *BalanceFlowUpsert) ClearType() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldType)
	return u
}

// SetAmount sets the "amount" field.
func (u *BalanceFlowUpsert) SetAmount(v float64) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateAmount() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *BalanceFlowUpsert) AddAmount(v float64) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldAmount, v)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *BalanceFlowUpsert) ClearAmount() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldAmount)
	return u
}

// SetConvertedAmount sets the "converted_amount" field.
func (u *BalanceFlowUpsert) SetConvertedAmount(v float64) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldConvertedAmount, v)
	return u
}

// UpdateConvertedAmount sets the "converted_amount" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateConvertedAmount() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldConvertedAmount)
	return u
}

// AddConvertedAmount adds v to the "converted_amount" field.
func (u *BalanceFlowUpsert) AddConvertedAmount(v float64) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldConvertedAmount, v)
	return u
}

// ClearConvertedAmount clears the value of the "converted_amount" field.
func (u *BalanceFlowUpsert) ClearConvertedAmount() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldConvertedAmount)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *BalanceFlowUpsert) SetAccountID(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateAccountID() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *BalanceFlowUpsert) AddAccountID(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *BalanceFlowUpsert) ClearAccountID() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldAccountID)
	return u
}

// SetToAccountID sets the "to_account_id" field.
func (u *BalanceFlowUpsert) SetToAccountID(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldToAccountID, v)
	return u
}

// UpdateToAccountID sets the "to_account_id" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateToAccountID() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldToAccountID)
	return u
}

// AddToAccountID adds v to the "to_account_id" field.
func (u *BalanceFlowUpsert) AddToAccountID(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldToAccountID, v)
	return u
}

// ClearToAccountID clears the value of the "to_account_id" field.
func (u *BalanceFlowUpsert) ClearToAccountID() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldToAccountID)
	return u
}

// SetPayeeID sets the "payee_id" field.
func (u *BalanceFlowUpsert) SetPayeeID(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldPayeeID, v)
	return u
}

// UpdatePayeeID sets the "payee_id" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdatePayeeID() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldPayeeID)
	return u
}

// AddPayeeID adds v to the "payee_id" field.
func (u *BalanceFlowUpsert) AddPayeeID(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldPayeeID, v)
	return u
}

// ClearPayeeID clears the value of the "payee_id" field.
func (u *BalanceFlowUpsert) ClearPayeeID() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldPayeeID)
	return u
}

// SetCreatorID sets the "creator_id" field.
func (u *BalanceFlowUpsert) SetCreatorID(v uint32) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldCreatorID, v)
	return u
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateCreatorID() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldCreatorID)
	return u
}

// AddCreatorID adds v to the "creator_id" field.
func (u *BalanceFlowUpsert) AddCreatorID(v uint32) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldCreatorID, v)
	return u
}

// ClearCreatorID clears the value of the "creator_id" field.
func (u *BalanceFlowUpsert) ClearCreatorID() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldCreatorID)
	return u
}

// SetCreateTime sets the "create_time" field.
func (u *BalanceFlowUpsert) SetCreateTime(v int64) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldCreateTime, v)
	return u
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateCreateTime() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldCreateTime)
	return u
}

// AddCreateTime adds v to the "create_time" field.
func (u *BalanceFlowUpsert) AddCreateTime(v int64) *BalanceFlowUpsert {
	u.Add(balanceflow.FieldCreateTime, v)
	return u
}

// ClearCreateTime clears the value of the "create_time" field.
func (u *BalanceFlowUpsert) ClearCreateTime() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldCreateTime)
	return u
}

// SetTitle sets the "title" field.
func (u *BalanceFlowUpsert) SetTitle(v string) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateTitle() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *BalanceFlowUpsert) ClearTitle() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldTitle)
	return u
}

// SetNotes sets the "notes" field.
func (u *BalanceFlowUpsert) SetNotes(v string) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateNotes() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *BalanceFlowUpsert) ClearNotes() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldNotes)
	return u
}

// SetConfirm sets the "confirm" field.
func (u *BalanceFlowUpsert) SetConfirm(v bool) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldConfirm, v)
	return u
}

// UpdateConfirm sets the "confirm" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateConfirm() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldConfirm)
	return u
}

// ClearConfirm clears the value of the "confirm" field.
func (u *BalanceFlowUpsert) ClearConfirm() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldConfirm)
	return u
}

// SetInclude sets the "include" field.
func (u *BalanceFlowUpsert) SetInclude(v bool) *BalanceFlowUpsert {
	u.Set(balanceflow.FieldInclude, v)
	return u
}

// UpdateInclude sets the "include" field to the value that was provided on create.
func (u *BalanceFlowUpsert) UpdateInclude() *BalanceFlowUpsert {
	u.SetExcluded(balanceflow.FieldInclude)
	return u
}

// ClearInclude clears the value of the "include" field.
func (u *BalanceFlowUpsert) ClearInclude() *BalanceFlowUpsert {
	u.SetNull(balanceflow.FieldInclude)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BalanceFlow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(balanceflow.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BalanceFlowUpsertOne) UpdateNewValues() *BalanceFlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(balanceflow.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(balanceflow.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balanceflow.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.InsertAt(); exists {
			s.SetIgnore(balanceflow.FieldInsertAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceFlow.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceFlowUpsertOne) Ignore() *BalanceFlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceFlowUpsertOne) DoNothing() *BalanceFlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceFlowCreate.OnConflict
// documentation for more info.
func (u *BalanceFlowUpsertOne) Update(set func(*BalanceFlowUpsert)) *BalanceFlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceFlowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceFlowUpsertOne) SetUpdatedAt(v time.Time) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateUpdatedAt() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *BalanceFlowUpsertOne) ClearUpdatedAt() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BalanceFlowUpsertOne) SetDeletedAt(v time.Time) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateDeletedAt() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BalanceFlowUpsertOne) ClearDeletedAt() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *BalanceFlowUpsertOne) SetCreatedBy(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *BalanceFlowUpsertOne) AddCreatedBy(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateCreatedBy() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *BalanceFlowUpsertOne) ClearCreatedBy() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *BalanceFlowUpsertOne) SetUpdatedBy(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *BalanceFlowUpsertOne) AddUpdatedBy(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateUpdatedBy() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *BalanceFlowUpsertOne) ClearUpdatedBy() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *BalanceFlowUpsertOne) SetDeletedBy(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *BalanceFlowUpsertOne) AddDeletedBy(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateDeletedBy() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *BalanceFlowUpsertOne) ClearDeletedBy() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearDeletedBy()
	})
}

// SetBookID sets the "book_id" field.
func (u *BalanceFlowUpsertOne) SetBookID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetBookID(v)
	})
}

// AddBookID adds v to the "book_id" field.
func (u *BalanceFlowUpsertOne) AddBookID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddBookID(v)
	})
}

// UpdateBookID sets the "book_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateBookID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateBookID()
	})
}

// ClearBookID clears the value of the "book_id" field.
func (u *BalanceFlowUpsertOne) ClearBookID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearBookID()
	})
}

// SetType sets the "type" field.
func (u *BalanceFlowUpsertOne) SetType(v balanceflow.Type) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateType() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *BalanceFlowUpsertOne) ClearType() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearType()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceFlowUpsertOne) SetAmount(v float64) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceFlowUpsertOne) AddAmount(v float64) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateAmount() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *BalanceFlowUpsertOne) ClearAmount() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearAmount()
	})
}

// SetConvertedAmount sets the "converted_amount" field.
func (u *BalanceFlowUpsertOne) SetConvertedAmount(v float64) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetConvertedAmount(v)
	})
}

// AddConvertedAmount adds v to the "converted_amount" field.
func (u *BalanceFlowUpsertOne) AddConvertedAmount(v float64) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddConvertedAmount(v)
	})
}

// UpdateConvertedAmount sets the "converted_amount" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateConvertedAmount() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateConvertedAmount()
	})
}

// ClearConvertedAmount clears the value of the "converted_amount" field.
func (u *BalanceFlowUpsertOne) ClearConvertedAmount() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearConvertedAmount()
	})
}

// SetAccountID sets the "account_id" field.
func (u *BalanceFlowUpsertOne) SetAccountID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *BalanceFlowUpsertOne) AddAccountID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateAccountID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *BalanceFlowUpsertOne) ClearAccountID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearAccountID()
	})
}

// SetToAccountID sets the "to_account_id" field.
func (u *BalanceFlowUpsertOne) SetToAccountID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetToAccountID(v)
	})
}

// AddToAccountID adds v to the "to_account_id" field.
func (u *BalanceFlowUpsertOne) AddToAccountID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddToAccountID(v)
	})
}

// UpdateToAccountID sets the "to_account_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateToAccountID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateToAccountID()
	})
}

// ClearToAccountID clears the value of the "to_account_id" field.
func (u *BalanceFlowUpsertOne) ClearToAccountID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearToAccountID()
	})
}

// SetPayeeID sets the "payee_id" field.
func (u *BalanceFlowUpsertOne) SetPayeeID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetPayeeID(v)
	})
}

// AddPayeeID adds v to the "payee_id" field.
func (u *BalanceFlowUpsertOne) AddPayeeID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddPayeeID(v)
	})
}

// UpdatePayeeID sets the "payee_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdatePayeeID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdatePayeeID()
	})
}

// ClearPayeeID clears the value of the "payee_id" field.
func (u *BalanceFlowUpsertOne) ClearPayeeID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearPayeeID()
	})
}

// SetCreatorID sets the "creator_id" field.
func (u *BalanceFlowUpsertOne) SetCreatorID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetCreatorID(v)
	})
}

// AddCreatorID adds v to the "creator_id" field.
func (u *BalanceFlowUpsertOne) AddCreatorID(v uint32) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddCreatorID(v)
	})
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateCreatorID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateCreatorID()
	})
}

// ClearCreatorID clears the value of the "creator_id" field.
func (u *BalanceFlowUpsertOne) ClearCreatorID() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearCreatorID()
	})
}

// SetCreateTime sets the "create_time" field.
func (u *BalanceFlowUpsertOne) SetCreateTime(v int64) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetCreateTime(v)
	})
}

// AddCreateTime adds v to the "create_time" field.
func (u *BalanceFlowUpsertOne) AddCreateTime(v int64) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddCreateTime(v)
	})
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateCreateTime() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateCreateTime()
	})
}

// ClearCreateTime clears the value of the "create_time" field.
func (u *BalanceFlowUpsertOne) ClearCreateTime() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearCreateTime()
	})
}

// SetTitle sets the "title" field.
func (u *BalanceFlowUpsertOne) SetTitle(v string) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateTitle() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *BalanceFlowUpsertOne) ClearTitle() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearTitle()
	})
}

// SetNotes sets the "notes" field.
func (u *BalanceFlowUpsertOne) SetNotes(v string) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateNotes() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BalanceFlowUpsertOne) ClearNotes() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearNotes()
	})
}

// SetConfirm sets the "confirm" field.
func (u *BalanceFlowUpsertOne) SetConfirm(v bool) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetConfirm(v)
	})
}

// UpdateConfirm sets the "confirm" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateConfirm() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateConfirm()
	})
}

// ClearConfirm clears the value of the "confirm" field.
func (u *BalanceFlowUpsertOne) ClearConfirm() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearConfirm()
	})
}

// SetInclude sets the "include" field.
func (u *BalanceFlowUpsertOne) SetInclude(v bool) *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetInclude(v)
	})
}

// UpdateInclude sets the "include" field to the value that was provided on create.
func (u *BalanceFlowUpsertOne) UpdateInclude() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateInclude()
	})
}

// ClearInclude clears the value of the "include" field.
func (u *BalanceFlowUpsertOne) ClearInclude() *BalanceFlowUpsertOne {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearInclude()
	})
}

// Exec executes the query.
func (u *BalanceFlowUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceFlowCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceFlowUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceFlowUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceFlowUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceFlowCreateBulk is the builder for creating many BalanceFlow entities in bulk.
type BalanceFlowCreateBulk struct {
	config
	err      error
	builders []*BalanceFlowCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceFlow entities in the database.
func (_c *BalanceFlowCreateBulk) Save(ctx context.Context) ([]*BalanceFlow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceFlow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceFlowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceFlowCreateBulk) SaveX(ctx context.Context) []*BalanceFlow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceFlowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceFlowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceFlow.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceFlowUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceFlowCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceFlowUpsertBulk {
	_c.conflict = opts
	return &BalanceFlowUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceFlow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceFlowCreateBulk) OnConflictColumns(columns ...string) *BalanceFlowUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceFlowUpsertBulk{
		create: _c,
	}
}

// BalanceFlowUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceFlow nodes.
type BalanceFlowUpsertBulk struct {
	create *BalanceFlowCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceFlow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(balanceflow.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BalanceFlowUpsertBulk) UpdateNewValues() *BalanceFlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(balanceflow.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(balanceflow.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balanceflow.FieldCreatedAt)
			}
			if _, exists := b.mutation.InsertAt(); exists {
				s.SetIgnore(balanceflow.FieldInsertAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceFlow.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceFlowUpsertBulk) Ignore() *BalanceFlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceFlowUpsertBulk) DoNothing() *BalanceFlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceFlowCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceFlowUpsertBulk) Update(set func(*BalanceFlowUpsert)) *BalanceFlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceFlowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceFlowUpsertBulk) SetUpdatedAt(v time.Time) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateUpdatedAt() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *BalanceFlowUpsertBulk) ClearUpdatedAt() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BalanceFlowUpsertBulk) SetDeletedAt(v time.Time) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateDeletedAt() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BalanceFlowUpsertBulk) ClearDeletedAt() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *BalanceFlowUpsertBulk) SetCreatedBy(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *BalanceFlowUpsertBulk) AddCreatedBy(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateCreatedBy() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *BalanceFlowUpsertBulk) ClearCreatedBy() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *BalanceFlowUpsertBulk) SetUpdatedBy(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *BalanceFlowUpsertBulk) AddUpdatedBy(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateUpdatedBy() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *BalanceFlowUpsertBulk) ClearUpdatedBy() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *BalanceFlowUpsertBulk) SetDeletedBy(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *BalanceFlowUpsertBulk) AddDeletedBy(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateDeletedBy() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *BalanceFlowUpsertBulk) ClearDeletedBy() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearDeletedBy()
	})
}

// SetBookID sets the "book_id" field.
func (u *BalanceFlowUpsertBulk) SetBookID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetBookID(v)
	})
}

// AddBookID adds v to the "book_id" field.
func (u *BalanceFlowUpsertBulk) AddBookID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddBookID(v)
	})
}

// UpdateBookID sets the "book_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateBookID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateBookID()
	})
}

// ClearBookID clears the value of the "book_id" field.
func (u *BalanceFlowUpsertBulk) ClearBookID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearBookID()
	})
}

// SetType sets the "type" field.
func (u *BalanceFlowUpsertBulk) SetType(v balanceflow.Type) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateType() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *BalanceFlowUpsertBulk) ClearType() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearType()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceFlowUpsertBulk) SetAmount(v float64) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceFlowUpsertBulk) AddAmount(v float64) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateAmount() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *BalanceFlowUpsertBulk) ClearAmount() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearAmount()
	})
}

// SetConvertedAmount sets the "converted_amount" field.
func (u *BalanceFlowUpsertBulk) SetConvertedAmount(v float64) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetConvertedAmount(v)
	})
}

// AddConvertedAmount adds v to the "converted_amount" field.
func (u *BalanceFlowUpsertBulk) AddConvertedAmount(v float64) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddConvertedAmount(v)
	})
}

// UpdateConvertedAmount sets the "converted_amount" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateConvertedAmount() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateConvertedAmount()
	})
}

// ClearConvertedAmount clears the value of the "converted_amount" field.
func (u *BalanceFlowUpsertBulk) ClearConvertedAmount() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearConvertedAmount()
	})
}

// SetAccountID sets the "account_id" field.
func (u *BalanceFlowUpsertBulk) SetAccountID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *BalanceFlowUpsertBulk) AddAccountID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateAccountID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *BalanceFlowUpsertBulk) ClearAccountID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearAccountID()
	})
}

// SetToAccountID sets the "to_account_id" field.
func (u *BalanceFlowUpsertBulk) SetToAccountID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetToAccountID(v)
	})
}

// AddToAccountID adds v to the "to_account_id" field.
func (u *BalanceFlowUpsertBulk) AddToAccountID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddToAccountID(v)
	})
}

// UpdateToAccountID sets the "to_account_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateToAccountID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateToAccountID()
	})
}

// ClearToAccountID clears the value of the "to_account_id" field.
func (u *BalanceFlowUpsertBulk) ClearToAccountID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearToAccountID()
	})
}

// SetPayeeID sets the "payee_id" field.
func (u *BalanceFlowUpsertBulk) SetPayeeID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetPayeeID(v)
	})
}

// AddPayeeID adds v to the "payee_id" field.
func (u *BalanceFlowUpsertBulk) AddPayeeID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddPayeeID(v)
	})
}

// UpdatePayeeID sets the "payee_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdatePayeeID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdatePayeeID()
	})
}

// ClearPayeeID clears the value of the "payee_id" field.
func (u *BalanceFlowUpsertBulk) ClearPayeeID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearPayeeID()
	})
}

// SetCreatorID sets the "creator_id" field.
func (u *BalanceFlowUpsertBulk) SetCreatorID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetCreatorID(v)
	})
}

// AddCreatorID adds v to the "creator_id" field.
func (u *BalanceFlowUpsertBulk) AddCreatorID(v uint32) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddCreatorID(v)
	})
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateCreatorID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateCreatorID()
	})
}

// ClearCreatorID clears the value of the "creator_id" field.
func (u *BalanceFlowUpsertBulk) ClearCreatorID() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearCreatorID()
	})
}

// SetCreateTime sets the "create_time" field.
func (u *BalanceFlowUpsertBulk) SetCreateTime(v int64) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetCreateTime(v)
	})
}

// AddCreateTime adds v to the "create_time" field.
func (u *BalanceFlowUpsertBulk) AddCreateTime(v int64) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.AddCreateTime(v)
	})
}

// UpdateCreateTime sets the "create_time" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateCreateTime() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateCreateTime()
	})
}

// ClearCreateTime clears the value of the "create_time" field.
func (u *BalanceFlowUpsertBulk) ClearCreateTime() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearCreateTime()
	})
}

// SetTitle sets the "title" field.
func (u *BalanceFlowUpsertBulk) SetTitle(v string) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateTitle() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *BalanceFlowUpsertBulk) ClearTitle() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearTitle()
	})
}

// SetNotes sets the "notes" field.
func (u *BalanceFlowUpsertBulk) SetNotes(v string) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateNotes() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *BalanceFlowUpsertBulk) ClearNotes() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearNotes()
	})
}

// SetConfirm sets the "confirm" field.
func (u *BalanceFlowUpsertBulk) SetConfirm(v bool) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetConfirm(v)
	})
}

// UpdateConfirm sets the "confirm" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateConfirm() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateConfirm()
	})
}

// ClearConfirm clears the value of the "confirm" field.
func (u *BalanceFlowUpsertBulk) ClearConfirm() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearConfirm()
	})
}

// SetInclude sets the "include" field.
func (u *BalanceFlowUpsertBulk) SetInclude(v bool) *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.SetInclude(v)
	})
}

// UpdateInclude sets the "include" field to the value that was provided on create.
func (u *BalanceFlowUpsertBulk) UpdateInclude() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.UpdateInclude()
	})
}

// ClearInclude clears the value of the "include" field.
func (u *BalanceFlowUpsertBulk) ClearInclude() *BalanceFlowUpsertBulk {
	return u.Update(func(s *BalanceFlowUpsert) {
		s.ClearInclude()
	})
}

// Exec executes the query.
func (u *BalanceFlowUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceFlowCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceFlowCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceFlowUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
