// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/budget"
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetUpdate is the builder for updating Budget entities.
type BudgetUpdate struct {
	config
	hooks     []Hook
	mutation  *BudgetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BudgetUpdate builder.
func (_u *BudgetUpdate) Where(ps ...predicate.Budget) *BudgetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BudgetUpdate) SetUpdatedAt(v time.Time) *BudgetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableUpdatedAt(v *time.Time) *BudgetUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *BudgetUpdate) ClearUpdatedAt() *BudgetUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BudgetUpdate) SetDeletedAt(v time.Time) *BudgetUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableDeletedAt(v *time.Time) *BudgetUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BudgetUpdate) ClearDeletedAt() *BudgetUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BudgetUpdate) SetCreatedBy(v uint32) *BudgetUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableCreatedBy(v *uint32) *BudgetUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *BudgetUpdate) AddCreatedBy(v int32) *BudgetUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BudgetUpdate) ClearCreatedBy() *BudgetUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BudgetUpdate) SetUpdatedBy(v uint32) *BudgetUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableUpdatedBy(v *uint32) *BudgetUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *BudgetUpdate) AddUpdatedBy(v int32) *BudgetUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BudgetUpdate) ClearUpdatedBy() *BudgetUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *BudgetUpdate) SetDeletedBy(v uint32) *BudgetUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableDeletedBy(v *uint32) *BudgetUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *BudgetUpdate) AddDeletedBy(v int32) *BudgetUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *BudgetUpdate) ClearDeletedBy() *BudgetUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *BudgetUpdate) SetBookID(v uint32) *BudgetUpdate {
	_u.mutation.ResetBookID()
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableBookID(v *uint32) *BudgetUpdate {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// AddBookID adds value to the "book_id" field.
func (_u *BudgetUpdate) AddBookID(v int32) *BudgetUpdate {
	_u.mutation.AddBookID(v)
	return _u
}

// ClearBookID clears the value of the "book_id" field.
func (_u *BudgetUpdate) ClearBookID() *BudgetUpdate {
	_u.mutation.ClearBookID()
	return _u
}

// SetName sets the "name" field.
func (_u *BudgetUpdate) SetName(v string) *BudgetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableName(v *string) *BudgetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *BudgetUpdate) ClearName() *BudgetUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetPeriod sets the "period" field.
func (_u *BudgetUpdate) SetPeriod(v budget.Period) *BudgetUpdate {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillablePeriod(v *budget.Period) *BudgetUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// ClearPeriod clears the value of the "period" field.
func (_u *BudgetUpdate) ClearPeriod() *BudgetUpdate {
	_u.mutation.ClearPeriod()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BudgetUpdate) SetAmount(v float64) *BudgetUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableAmount(v *float64) *BudgetUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BudgetUpdate) AddAmount(v float64) *BudgetUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// ClearAmount clears the value of the "amount" field.
func (_u *BudgetUpdate) ClearAmount() *BudgetUpdate {
	_u.mutation.ClearAmount()
	return _u
}

// SetUsedAmount sets the "used_amount" field.
func (_u *BudgetUpdate) SetUsedAmount(v float64) *BudgetUpdate {
	_u.mutation.ResetUsedAmount()
	_u.mutation.SetUsedAmount(v)
	return _u
}

// SetNillableUsedAmount sets the "used_amount" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableUsedAmount(v *float64) *BudgetUpdate {
	if v != nil {
		_u.SetUsedAmount(*v)
	}
	return _u
}

// AddUsedAmount adds value to the "used_amount" field.
func (_u *BudgetUpdate) AddUsedAmount(v float64) *BudgetUpdate {
	_u.mutation.AddUsedAmount(v)
	return _u
}

// ClearUsedAmount clears the value of the "used_amount" field.
func (_u *BudgetUpdate) ClearUsedAmount() *BudgetUpdate {
	_u.mutation.ClearUsedAmount()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *BudgetUpdate) SetCategoryID(v uint32) *BudgetUpdate {
	_u.mutation.ResetCategoryID()
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableCategoryID(v *uint32) *BudgetUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// AddCategoryID adds value to the "category_id" field.
func (_u *BudgetUpdate) AddCategoryID(v int32) *BudgetUpdate {
	_u.mutation.AddCategoryID(v)
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *BudgetUpdate) ClearCategoryID() *BudgetUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *BudgetUpdate) SetAccountID(v uint32) *BudgetUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableAccountID(v *uint32) *BudgetUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *BudgetUpdate) AddAccountID(v int32) *BudgetUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *BudgetUpdate) ClearAccountID() *BudgetUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *BudgetUpdate) SetStartDate(v int64) *BudgetUpdate {
	_u.mutation.ResetStartDate()
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableStartDate(v *int64) *BudgetUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// AddStartDate adds value to the "start_date" field.
func (_u *BudgetUpdate) AddStartDate(v int64) *BudgetUpdate {
	_u.mutation.AddStartDate(v)
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *BudgetUpdate) ClearStartDate() *BudgetUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *BudgetUpdate) SetEndDate(v int64) *BudgetUpdate {
	_u.mutation.ResetEndDate()
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableEndDate(v *int64) *BudgetUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// AddEndDate adds value to the "end_date" field.
func (_u *BudgetUpdate) AddEndDate(v int64) *BudgetUpdate {
	_u.mutation.AddEndDate(v)
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *BudgetUpdate) ClearEndDate() *BudgetUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetEnable sets the "enable" field.
func (_u *BudgetUpdate) SetEnable(v bool) *BudgetUpdate {
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableEnable(v *bool) *BudgetUpdate {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// ClearEnable clears the value of the "enable" field.
func (_u *BudgetUpdate) ClearEnable() *BudgetUpdate {
	_u.mutation.ClearEnable()
	return _u
}

// SetNotify sets the "notify" field.
func (_u *BudgetUpdate) SetNotify(v bool) *BudgetUpdate {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableNotify(v *bool) *BudgetUpdate {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// ClearNotify clears the value of the "notify" field.
func (_u *BudgetUpdate) ClearNotify() *BudgetUpdate {
	_u.mutation.ClearNotify()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BudgetUpdate) SetNotes(v string) *BudgetUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableNotes(v *string) *BudgetUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BudgetUpdate) ClearNotes() *BudgetUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the BudgetMutation object of the builder.
func (_u *BudgetUpdate) Mutation() *BudgetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BudgetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BudgetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := budget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Budget.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Period(); ok {
		if err := budget.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "Budget.period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := budget.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Budget.notes": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BudgetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BudgetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BudgetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(budget.FieldTenantID, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(budget.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(budget.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(budget.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(budget.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(budget.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(budget.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(budget.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(budget.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(budget.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(budget.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(budget.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(budget.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(budget.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(budget.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(budget.FieldBookID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBookID(); ok {
		_spec.AddField(budget.FieldBookID, field.TypeUint32, value)
	}
	if _u.mutation.BookIDCleared() {
		_spec.ClearField(budget.FieldBookID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(budget.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(budget.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeEnum, value)
	}
	if _u.mutation.PeriodCleared() {
		_spec.ClearField(budget.FieldPeriod, field.TypeEnum)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.AmountCleared() {
		_spec.ClearField(budget.FieldAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UsedAmount(); ok {
		_spec.SetField(budget.FieldUsedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedAmount(); ok {
		_spec.AddField(budget.FieldUsedAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UsedAmountCleared() {
		_spec.ClearField(budget.FieldUsedAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(budget.FieldCategoryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCategoryID(); ok {
		_spec.AddField(budget.FieldCategoryID, field.TypeUint32, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(budget.FieldCategoryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(budget.FieldAccountID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(budget.FieldAccountID, field.TypeUint32, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(budget.FieldAccountID, field.TypeUint32)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(budget.FieldStartDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartDate(); ok {
		_spec.AddField(budget.FieldStartDate, field.TypeInt64, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(budget.FieldStartDate, field.TypeInt64)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(budget.FieldEndDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndDate(); ok {
		_spec.AddField(budget.FieldEndDate, field.TypeInt64, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(budget.FieldEndDate, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(budget.FieldEnable, field.TypeBool, value)
	}
	if _u.mutation.EnableCleared() {
		_spec.ClearField(budget.FieldEnable, field.TypeBool)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(budget.FieldNotify, field.TypeBool, value)
	}
	if _u.mutation.NotifyCleared() {
		_spec.ClearField(budget.FieldNotify, field.TypeBool)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(budget.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(budget.FieldNotes, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BudgetUpdateOne is the builder for updating a single Budget entity.
type BudgetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BudgetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BudgetUpdateOne) SetUpdatedAt(v time.Time) *BudgetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableUpdatedAt(v *time.Time) *BudgetUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *BudgetUpdateOne) ClearUpdatedAt() *BudgetUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BudgetUpdateOne) SetDeletedAt(v time.Time) *BudgetUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableDeletedAt(v *time.Time) *BudgetUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BudgetUpdateOne) ClearDeletedAt() *BudgetUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BudgetUpdateOne) SetCreatedBy(v uint32) *BudgetUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableCreatedBy(v *uint32) *BudgetUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *BudgetUpdateOne) AddCreatedBy(v int32) *BudgetUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *BudgetUpdateOne) ClearCreatedBy() *BudgetUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BudgetUpdateOne) SetUpdatedBy(v uint32) *BudgetUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableUpdatedBy(v *uint32) *BudgetUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *BudgetUpdateOne) AddUpdatedBy(v int32) *BudgetUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *BudgetUpdateOne) ClearUpdatedBy() *BudgetUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *BudgetUpdateOne) SetDeletedBy(v uint32) *BudgetUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableDeletedBy(v *uint32) *BudgetUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *BudgetUpdateOne) AddDeletedBy(v int32) *BudgetUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *BudgetUpdateOne) ClearDeletedBy() *BudgetUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *BudgetUpdateOne) SetBookID(v uint32) *BudgetUpdateOne {
	_u.mutation.ResetBookID()
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableBookID(v *uint32) *BudgetUpdateOne {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// AddBookID adds value to the "book_id" field.
func (_u *BudgetUpdateOne) AddBookID(v int32) *BudgetUpdateOne {
	_u.mutation.AddBookID(v)
	return _u
}

// ClearBookID clears the value of the "book_id" field.
func (_u *BudgetUpdateOne) ClearBookID() *BudgetUpdateOne {
	_u.mutation.ClearBookID()
	return _u
}

// SetName sets the "name" field.
func (_u *BudgetUpdateOne) SetName(v string) *BudgetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableName(v *string) *BudgetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *BudgetUpdateOne) ClearName() *BudgetUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetPeriod sets the "period" field.
func (_u *BudgetUpdateOne) SetPeriod(v budget.Period) *BudgetUpdateOne {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillablePeriod(v *budget.Period) *BudgetUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// ClearPeriod clears the value of the "period" field.
func (_u *BudgetUpdateOne) ClearPeriod() *BudgetUpdateOne {
	_u.mutation.ClearPeriod()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BudgetUpdateOne) SetAmount(v float64) *BudgetUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableAmount(v *float64) *BudgetUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BudgetUpdateOne) AddAmount(v float64) *BudgetUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// ClearAmount clears the value of the "amount" field.
func (_u *BudgetUpdateOne) ClearAmount() *BudgetUpdateOne {
	_u.mutation.ClearAmount()
	return _u
}

// SetUsedAmount sets the "used_amount" field.
func (_u *BudgetUpdateOne) SetUsedAmount(v float64) *BudgetUpdateOne {
	_u.mutation.ResetUsedAmount()
	_u.mutation.SetUsedAmount(v)
	return _u
}

// SetNillableUsedAmount sets the "used_amount" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableUsedAmount(v *float64) *BudgetUpdateOne {
	if v != nil {
		_u.SetUsedAmount(*v)
	}
	return _u
}

// AddUsedAmount adds value to the "used_amount" field.
func (_u *BudgetUpdateOne) AddUsedAmount(v float64) *BudgetUpdateOne {
	_u.mutation.AddUsedAmount(v)
	return _u
}

// ClearUsedAmount clears the value of the "used_amount" field.
func (_u *BudgetUpdateOne) ClearUsedAmount() *BudgetUpdateOne {
	_u.mutation.ClearUsedAmount()
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *BudgetUpdateOne) SetCategoryID(v uint32) *BudgetUpdateOne {
	_u.mutation.ResetCategoryID()
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableCategoryID(v *uint32) *BudgetUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// AddCategoryID adds value to the "category_id" field.
func (_u *BudgetUpdateOne) AddCategoryID(v int32) *BudgetUpdateOne {
	_u.mutation.AddCategoryID(v)
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *BudgetUpdateOne) ClearCategoryID() *BudgetUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *BudgetUpdateOne) SetAccountID(v uint32) *BudgetUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableAccountID(v *uint32) *BudgetUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *BudgetUpdateOne) AddAccountID(v int32) *BudgetUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *BudgetUpdateOne) ClearAccountID() *BudgetUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *BudgetUpdateOne) SetStartDate(v int64) *BudgetUpdateOne {
	_u.mutation.ResetStartDate()
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableStartDate(v *int64) *BudgetUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// AddStartDate adds value to the "start_date" field.
func (_u *BudgetUpdateOne) AddStartDate(v int64) *BudgetUpdateOne {
	_u.mutation.AddStartDate(v)
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *BudgetUpdateOne) ClearStartDate() *BudgetUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *BudgetUpdateOne) SetEndDate(v int64) *BudgetUpdateOne {
	_u.mutation.ResetEndDate()
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableEndDate(v *int64) *BudgetUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// AddEndDate adds value to the "end_date" field.
func (_u *BudgetUpdateOne) AddEndDate(v int64) *BudgetUpdateOne {
	_u.mutation.AddEndDate(v)
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *BudgetUpdateOne) ClearEndDate() *BudgetUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetEnable sets the "enable" field.
func (_u *BudgetUpdateOne) SetEnable(v bool) *BudgetUpdateOne {
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableEnable(v *bool) *BudgetUpdateOne {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// ClearEnable clears the value of the "enable" field.
func (_u *BudgetUpdateOne) ClearEnable() *BudgetUpdateOne {
	_u.mutation.ClearEnable()
	return _u
}

// SetNotify sets the "notify" field.
func (_u *BudgetUpdateOne) SetNotify(v bool) *BudgetUpdateOne {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableNotify(v *bool) *BudgetUpdateOne {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// ClearNotify clears the value of the "notify" field.
func (_u *BudgetUpdateOne) ClearNotify() *BudgetUpdateOne {
	_u.mutation.ClearNotify()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BudgetUpdateOne) SetNotes(v string) *BudgetUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableNotes(v *string) *BudgetUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BudgetUpdateOne) ClearNotes() *BudgetUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the BudgetMutation object of the builder.
func (_u *BudgetUpdateOne) Mutation() *BudgetMutation {
	return _u.mutation
}

// Where appends a list predicates to the BudgetUpdate builder.
func (_u *BudgetUpdateOne) Where(ps ...predicate.Budget) *BudgetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BudgetUpdateOne) Select(field string, fields ...string) *BudgetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Budget entity.
func (_u *BudgetUpdateOne) Save(ctx context.Context) (*Budget, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetUpdateOne) SaveX(ctx context.Context) *Budget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BudgetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := budget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Budget.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Period(); ok {
		if err := budget.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "Budget.period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := budget.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Budget.notes": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BudgetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BudgetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BudgetUpdateOne) sqlSave(ctx context.Context) (_node *Budget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Budget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budget.FieldID)
		for _, f := range fields {
			if !budget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(budget.FieldTenantID, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(budget.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(budget.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(budget.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(budget.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(budget.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(budget.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(budget.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(budget.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(budget.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(budget.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(budget.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(budget.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(budget.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(budget.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(budget.FieldBookID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBookID(); ok {
		_spec.AddField(budget.FieldBookID, field.TypeUint32, value)
	}
	if _u.mutation.BookIDCleared() {
		_spec.ClearField(budget.FieldBookID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(budget.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(budget.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeEnum, value)
	}
	if _u.mutation.PeriodCleared() {
		_spec.ClearField(budget.FieldPeriod, field.TypeEnum)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.AmountCleared() {
		_spec.ClearField(budget.FieldAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UsedAmount(); ok {
		_spec.SetField(budget.FieldUsedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedAmount(); ok {
		_spec.AddField(budget.FieldUsedAmount, field.TypeFloat64, value)
	}
	if _u.mutation.UsedAmountCleared() {
		_spec.ClearField(budget.FieldUsedAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(budget.FieldCategoryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCategoryID(); ok {
		_spec.AddField(budget.FieldCategoryID, field.TypeUint32, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(budget.FieldCategoryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(budget.FieldAccountID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(budget.FieldAccountID, field.TypeUint32, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(budget.FieldAccountID, field.TypeUint32)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(budget.FieldStartDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartDate(); ok {
		_spec.AddField(budget.FieldStartDate, field.TypeInt64, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(budget.FieldStartDate, field.TypeInt64)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(budget.FieldEndDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndDate(); ok {
		_spec.AddField(budget.FieldEndDate, field.TypeInt64, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(budget.FieldEndDate, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(budget.FieldEnable, field.TypeBool, value)
	}
	if _u.mutation.EnableCleared() {
		_spec.ClearField(budget.FieldEnable, field.TypeBool)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(budget.FieldNotify, field.TypeBool, value)
	}
	if _u.mutation.NotifyCleared() {
		_spec.ClearField(budget.FieldNotify, field.TypeBool)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(budget.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(budget.FieldNotes, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Budget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
