// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-ledger/app/core/service/internal/data/ent/dictentryi18n"
	"go-wind-ledger/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictEntryI18nUpdate is the builder for updating DictEntryI18n entities.
type DictEntryI18nUpdate struct {
	config
	hooks     []Hook
	mutation  *DictEntryI18nMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DictEntryI18nUpdate builder.
func (_u *DictEntryI18nUpdate) Where(ps ...predicate.DictEntryI18n) *DictEntryI18nUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictEntryI18nUpdate) SetUpdatedAt(v time.Time) *DictEntryI18nUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableUpdatedAt(v *time.Time) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictEntryI18nUpdate) ClearUpdatedAt() *DictEntryI18nUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictEntryI18nUpdate) SetDeletedAt(v time.Time) *DictEntryI18nUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableDeletedAt(v *time.Time) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictEntryI18nUpdate) ClearDeletedAt() *DictEntryI18nUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictEntryI18nUpdate) SetCreatedBy(v uint32) *DictEntryI18nUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableCreatedBy(v *uint32) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictEntryI18nUpdate) AddCreatedBy(v int32) *DictEntryI18nUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictEntryI18nUpdate) ClearCreatedBy() *DictEntryI18nUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictEntryI18nUpdate) SetUpdatedBy(v uint32) *DictEntryI18nUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableUpdatedBy(v *uint32) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictEntryI18nUpdate) AddUpdatedBy(v int32) *DictEntryI18nUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictEntryI18nUpdate) ClearUpdatedBy() *DictEntryI18nUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictEntryI18nUpdate) SetDeletedBy(v uint32) *DictEntryI18nUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableDeletedBy(v *uint32) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictEntryI18nUpdate) AddDeletedBy(v int32) *DictEntryI18nUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictEntryI18nUpdate) ClearDeletedBy() *DictEntryI18nUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDictEntryID sets the "dict_entry_id" field.
func (_u *DictEntryI18nUpdate) SetDictEntryID(v uint32) *DictEntryI18nUpdate {
	_u.mutation.ResetDictEntryID()
	_u.mutation.SetDictEntryID(v)
	return _u
}

// SetNillableDictEntryID sets the "dict_entry_id" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableDictEntryID(v *uint32) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetDictEntryID(*v)
	}
	return _u
}

// AddDictEntryID adds value to the "dict_entry_id" field.
func (_u *DictEntryI18nUpdate) AddDictEntryID(v int32) *DictEntryI18nUpdate {
	_u.mutation.AddDictEntryID(v)
	return _u
}

// ClearDictEntryID clears the value of the "dict_entry_id" field.
func (_u *DictEntryI18nUpdate) ClearDictEntryID() *DictEntryI18nUpdate {
	_u.mutation.ClearDictEntryID()
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *DictEntryI18nUpdate) SetLanguageCode(v string) *DictEntryI18nUpdate {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableLanguageCode(v *string) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (_u *DictEntryI18nUpdate) ClearLanguageCode() *DictEntryI18nUpdate {
	_u.mutation.ClearLanguageCode()
	return _u
}

// SetName sets the "name" field.
func (_u *DictEntryI18nUpdate) SetName(v string) *DictEntryI18nUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictEntryI18nUpdate) SetNillableName(v *string) *DictEntryI18nUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DictEntryI18nUpdate) ClearName() *DictEntryI18nUpdate {
	_u.mutation.ClearName()
	return _u
}

// Mutation returns the DictEntryI18nMutation object of the builder.
func (_u *DictEntryI18nUpdate) Mutation() *DictEntryI18nMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictEntryI18nUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictEntryI18nUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictEntryI18nUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictEntryI18nUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictEntryI18nUpdate) check() error {
	if v, ok := _u.mutation.LanguageCode(); ok {
		if err := dictentryi18n.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "DictEntryI18n.language_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := dictentryi18n.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictEntryI18n.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictEntryI18nUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictEntryI18nUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictEntryI18nUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictentryi18n.Table, dictentryi18n.Columns, sqlgraph.NewFieldSpec(dictentryi18n.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dictentryi18n.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictentryi18n.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dictentryi18n.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictentryi18n.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictentryi18n.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dictentryi18n.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dictentryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dictentryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dictentryi18n.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dictentryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dictentryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dictentryi18n.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dictentryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dictentryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dictentryi18n.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DictEntryID(); ok {
		_spec.SetField(dictentryi18n.FieldDictEntryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDictEntryID(); ok {
		_spec.AddField(dictentryi18n.FieldDictEntryID, field.TypeUint32, value)
	}
	if _u.mutation.DictEntryIDCleared() {
		_spec.ClearField(dictentryi18n.FieldDictEntryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(dictentryi18n.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(dictentryi18n.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictentryi18n.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dictentryi18n.FieldName, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictentryi18n.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictEntryI18nUpdateOne is the builder for updating a single DictEntryI18n entity.
type DictEntryI18nUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DictEntryI18nMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictEntryI18nUpdateOne) SetUpdatedAt(v time.Time) *DictEntryI18nUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableUpdatedAt(v *time.Time) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictEntryI18nUpdateOne) ClearUpdatedAt() *DictEntryI18nUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictEntryI18nUpdateOne) SetDeletedAt(v time.Time) *DictEntryI18nUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableDeletedAt(v *time.Time) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictEntryI18nUpdateOne) ClearDeletedAt() *DictEntryI18nUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictEntryI18nUpdateOne) SetCreatedBy(v uint32) *DictEntryI18nUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableCreatedBy(v *uint32) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictEntryI18nUpdateOne) AddCreatedBy(v int32) *DictEntryI18nUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictEntryI18nUpdateOne) ClearCreatedBy() *DictEntryI18nUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictEntryI18nUpdateOne) SetUpdatedBy(v uint32) *DictEntryI18nUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableUpdatedBy(v *uint32) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictEntryI18nUpdateOne) AddUpdatedBy(v int32) *DictEntryI18nUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictEntryI18nUpdateOne) ClearUpdatedBy() *DictEntryI18nUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictEntryI18nUpdateOne) SetDeletedBy(v uint32) *DictEntryI18nUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableDeletedBy(v *uint32) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictEntryI18nUpdateOne) AddDeletedBy(v int32) *DictEntryI18nUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictEntryI18nUpdateOne) ClearDeletedBy() *DictEntryI18nUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetDictEntryID sets the "dict_entry_id" field.
func (_u *DictEntryI18nUpdateOne) SetDictEntryID(v uint32) *DictEntryI18nUpdateOne {
	_u.mutation.ResetDictEntryID()
	_u.mutation.SetDictEntryID(v)
	return _u
}

// SetNillableDictEntryID sets the "dict_entry_id" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableDictEntryID(v *uint32) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetDictEntryID(*v)
	}
	return _u
}

// AddDictEntryID adds value to the "dict_entry_id" field.
func (_u *DictEntryI18nUpdateOne) AddDictEntryID(v int32) *DictEntryI18nUpdateOne {
	_u.mutation.AddDictEntryID(v)
	return _u
}

// ClearDictEntryID clears the value of the "dict_entry_id" field.
func (_u *DictEntryI18nUpdateOne) ClearDictEntryID() *DictEntryI18nUpdateOne {
	_u.mutation.ClearDictEntryID()
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *DictEntryI18nUpdateOne) SetLanguageCode(v string) *DictEntryI18nUpdateOne {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableLanguageCode(v *string) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// ClearLanguageCode clears the value of the "language_code" field.
func (_u *DictEntryI18nUpdateOne) ClearLanguageCode() *DictEntryI18nUpdateOne {
	_u.mutation.ClearLanguageCode()
	return _u
}

// SetName sets the "name" field.
func (_u *DictEntryI18nUpdateOne) SetName(v string) *DictEntryI18nUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictEntryI18nUpdateOne) SetNillableName(v *string) *DictEntryI18nUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DictEntryI18nUpdateOne) ClearName() *DictEntryI18nUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// Mutation returns the DictEntryI18nMutation object of the builder.
func (_u *DictEntryI18nUpdateOne) Mutation() *DictEntryI18nMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictEntryI18nUpdate builder.
func (_u *DictEntryI18nUpdateOne) Where(ps ...predicate.DictEntryI18n) *DictEntryI18nUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictEntryI18nUpdateOne) Select(field string, fields ...string) *DictEntryI18nUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictEntryI18n entity.
func (_u *DictEntryI18nUpdateOne) Save(ctx context.Context) (*DictEntryI18n, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictEntryI18nUpdateOne) SaveX(ctx context.Context) *DictEntryI18n {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictEntryI18nUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictEntryI18nUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictEntryI18nUpdateOne) check() error {
	if v, ok := _u.mutation.LanguageCode(); ok {
		if err := dictentryi18n.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "DictEntryI18n.language_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := dictentryi18n.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictEntryI18n.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictEntryI18nUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictEntryI18nUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictEntryI18nUpdateOne) sqlSave(ctx context.Context) (_node *DictEntryI18n, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictentryi18n.Table, dictentryi18n.Columns, sqlgraph.NewFieldSpec(dictentryi18n.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictEntryI18n.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictentryi18n.FieldID)
		for _, f := range fields {
			if !dictentryi18n.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictentryi18n.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dictentryi18n.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictentryi18n.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dictentryi18n.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictentryi18n.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictentryi18n.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dictentryi18n.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dictentryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dictentryi18n.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dictentryi18n.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dictentryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dictentryi18n.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dictentryi18n.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dictentryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dictentryi18n.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dictentryi18n.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DictEntryID(); ok {
		_spec.SetField(dictentryi18n.FieldDictEntryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDictEntryID(); ok {
		_spec.AddField(dictentryi18n.FieldDictEntryID, field.TypeUint32, value)
	}
	if _u.mutation.DictEntryIDCleared() {
		_spec.ClearField(dictentryi18n.FieldDictEntryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(dictentryi18n.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.LanguageCodeCleared() {
		_spec.ClearField(dictentryi18n.FieldLanguageCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictentryi18n.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dictentryi18n.FieldName, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DictEntryI18n{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictentryi18n.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
