// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/dictentry"
	"go-wind-cms/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictEntryUpdate is the builder for updating DictEntry entities.
type DictEntryUpdate struct {
	config
	hooks     []Hook
	mutation  *DictEntryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DictEntryUpdate builder.
func (_u *DictEntryUpdate) Where(ps ...predicate.DictEntry) *DictEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictEntryUpdate) SetUpdatedAt(v time.Time) *DictEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableUpdatedAt(v *time.Time) *DictEntryUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictEntryUpdate) ClearUpdatedAt() *DictEntryUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictEntryUpdate) SetDeletedAt(v time.Time) *DictEntryUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableDeletedAt(v *time.Time) *DictEntryUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictEntryUpdate) ClearDeletedAt() *DictEntryUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictEntryUpdate) SetCreatedBy(v uint32) *DictEntryUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableCreatedBy(v *uint32) *DictEntryUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictEntryUpdate) AddCreatedBy(v int32) *DictEntryUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictEntryUpdate) ClearCreatedBy() *DictEntryUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictEntryUpdate) SetUpdatedBy(v uint32) *DictEntryUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableUpdatedBy(v *uint32) *DictEntryUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictEntryUpdate) AddUpdatedBy(v int32) *DictEntryUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictEntryUpdate) ClearUpdatedBy() *DictEntryUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictEntryUpdate) SetDeletedBy(v uint32) *DictEntryUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableDeletedBy(v *uint32) *DictEntryUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictEntryUpdate) AddDeletedBy(v int32) *DictEntryUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictEntryUpdate) ClearDeletedBy() *DictEntryUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DictEntryUpdate) SetRemark(v string) *DictEntryUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableRemark(v *string) *DictEntryUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DictEntryUpdate) ClearRemark() *DictEntryUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DictEntryUpdate) SetSortOrder(v uint32) *DictEntryUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableSortOrder(v *uint32) *DictEntryUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DictEntryUpdate) AddSortOrder(v int32) *DictEntryUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *DictEntryUpdate) ClearSortOrder() *DictEntryUpdate {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetDictTypeID sets the "dict_type_id" field.
func (_u *DictEntryUpdate) SetDictTypeID(v uint32) *DictEntryUpdate {
	_u.mutation.ResetDictTypeID()
	_u.mutation.SetDictTypeID(v)
	return _u
}

// SetNillableDictTypeID sets the "dict_type_id" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableDictTypeID(v *uint32) *DictEntryUpdate {
	if v != nil {
		_u.SetDictTypeID(*v)
	}
	return _u
}

// AddDictTypeID adds value to the "dict_type_id" field.
func (_u *DictEntryUpdate) AddDictTypeID(v int32) *DictEntryUpdate {
	_u.mutation.AddDictTypeID(v)
	return _u
}

// ClearDictTypeID clears the value of the "dict_type_id" field.
func (_u *DictEntryUpdate) ClearDictTypeID() *DictEntryUpdate {
	_u.mutation.ClearDictTypeID()
	return _u
}

// SetCode sets the "code" field.
func (_u *DictEntryUpdate) SetCode(v string) *DictEntryUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableCode(v *string) *DictEntryUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *DictEntryUpdate) ClearCode() *DictEntryUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetName sets the "name" field.
func (_u *DictEntryUpdate) SetName(v string) *DictEntryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableName(v *string) *DictEntryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DictEntryUpdate) ClearName() *DictEntryUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetValue sets the "value" field.
func (_u *DictEntryUpdate) SetValue(v string) *DictEntryUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *DictEntryUpdate) SetNillableValue(v *string) *DictEntryUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *DictEntryUpdate) ClearValue() *DictEntryUpdate {
	_u.mutation.ClearValue()
	return _u
}

// Mutation returns the DictEntryMutation object of the builder.
func (_u *DictEntryUpdate) Mutation() *DictEntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictEntryUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := dictentry.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DictEntry.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := dictentry.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictEntry.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := dictentry.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DictEntry.value": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictEntryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictEntryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictentry.Table, dictentry.Columns, sqlgraph.NewFieldSpec(dictentry.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dictentry.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dictentry.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictentry.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictentry.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dictentry.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dictentry.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dictentry.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dictentry.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dictentry.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dictentry.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dictentry.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dictentry.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dictentry.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dictentry.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dictentry.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(dictentry.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(dictentry.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(dictentry.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(dictentry.FieldSortOrder, field.TypeUint32)
	}
	if value, ok := _u.mutation.DictTypeID(); ok {
		_spec.SetField(dictentry.FieldDictTypeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDictTypeID(); ok {
		_spec.AddField(dictentry.FieldDictTypeID, field.TypeUint32, value)
	}
	if _u.mutation.DictTypeIDCleared() {
		_spec.ClearField(dictentry.FieldDictTypeID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(dictentry.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(dictentry.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictentry.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dictentry.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(dictentry.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(dictentry.FieldValue, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictEntryUpdateOne is the builder for updating a single DictEntry entity.
type DictEntryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DictEntryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictEntryUpdateOne) SetUpdatedAt(v time.Time) *DictEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableUpdatedAt(v *time.Time) *DictEntryUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *DictEntryUpdateOne) ClearUpdatedAt() *DictEntryUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictEntryUpdateOne) SetDeletedAt(v time.Time) *DictEntryUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableDeletedAt(v *time.Time) *DictEntryUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictEntryUpdateOne) ClearDeletedAt() *DictEntryUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DictEntryUpdateOne) SetCreatedBy(v uint32) *DictEntryUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableCreatedBy(v *uint32) *DictEntryUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DictEntryUpdateOne) AddCreatedBy(v int32) *DictEntryUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DictEntryUpdateOne) ClearCreatedBy() *DictEntryUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *DictEntryUpdateOne) SetUpdatedBy(v uint32) *DictEntryUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableUpdatedBy(v *uint32) *DictEntryUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *DictEntryUpdateOne) AddUpdatedBy(v int32) *DictEntryUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *DictEntryUpdateOne) ClearUpdatedBy() *DictEntryUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *DictEntryUpdateOne) SetDeletedBy(v uint32) *DictEntryUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableDeletedBy(v *uint32) *DictEntryUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *DictEntryUpdateOne) AddDeletedBy(v int32) *DictEntryUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *DictEntryUpdateOne) ClearDeletedBy() *DictEntryUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DictEntryUpdateOne) SetRemark(v string) *DictEntryUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableRemark(v *string) *DictEntryUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DictEntryUpdateOne) ClearRemark() *DictEntryUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *DictEntryUpdateOne) SetSortOrder(v uint32) *DictEntryUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableSortOrder(v *uint32) *DictEntryUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *DictEntryUpdateOne) AddSortOrder(v int32) *DictEntryUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *DictEntryUpdateOne) ClearSortOrder() *DictEntryUpdateOne {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetDictTypeID sets the "dict_type_id" field.
func (_u *DictEntryUpdateOne) SetDictTypeID(v uint32) *DictEntryUpdateOne {
	_u.mutation.ResetDictTypeID()
	_u.mutation.SetDictTypeID(v)
	return _u
}

// SetNillableDictTypeID sets the "dict_type_id" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableDictTypeID(v *uint32) *DictEntryUpdateOne {
	if v != nil {
		_u.SetDictTypeID(*v)
	}
	return _u
}

// AddDictTypeID adds value to the "dict_type_id" field.
func (_u *DictEntryUpdateOne) AddDictTypeID(v int32) *DictEntryUpdateOne {
	_u.mutation.AddDictTypeID(v)
	return _u
}

// ClearDictTypeID clears the value of the "dict_type_id" field.
func (_u *DictEntryUpdateOne) ClearDictTypeID() *DictEntryUpdateOne {
	_u.mutation.ClearDictTypeID()
	return _u
}

// SetCode sets the "code" field.
func (_u *DictEntryUpdateOne) SetCode(v string) *DictEntryUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableCode(v *string) *DictEntryUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *DictEntryUpdateOne) ClearCode() *DictEntryUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetName sets the "name" field.
func (_u *DictEntryUpdateOne) SetName(v string) *DictEntryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableName(v *string) *DictEntryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *DictEntryUpdateOne) ClearName() *DictEntryUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetValue sets the "value" field.
func (_u *DictEntryUpdateOne) SetValue(v string) *DictEntryUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *DictEntryUpdateOne) SetNillableValue(v *string) *DictEntryUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *DictEntryUpdateOne) ClearValue() *DictEntryUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// Mutation returns the DictEntryMutation object of the builder.
func (_u *DictEntryUpdateOne) Mutation() *DictEntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictEntryUpdate builder.
func (_u *DictEntryUpdateOne) Where(ps ...predicate.DictEntry) *DictEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictEntryUpdateOne) Select(field string, fields ...string) *DictEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictEntry entity.
func (_u *DictEntryUpdateOne) Save(ctx context.Context) (*DictEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictEntryUpdateOne) SaveX(ctx context.Context) *DictEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictEntryUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := dictentry.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DictEntry.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := dictentry.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictEntry.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := dictentry.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DictEntry.value": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DictEntryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DictEntryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DictEntryUpdateOne) sqlSave(ctx context.Context) (_node *DictEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictentry.Table, dictentry.Columns, sqlgraph.NewFieldSpec(dictentry.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictentry.FieldID)
		for _, f := range fields {
			if !dictentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(dictentry.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(dictentry.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictentry.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictentry.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dictentry.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dictentry.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dictentry.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(dictentry.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(dictentry.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(dictentry.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(dictentry.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(dictentry.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(dictentry.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dictentry.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dictentry.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(dictentry.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(dictentry.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(dictentry.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(dictentry.FieldSortOrder, field.TypeUint32)
	}
	if value, ok := _u.mutation.DictTypeID(); ok {
		_spec.SetField(dictentry.FieldDictTypeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDictTypeID(); ok {
		_spec.AddField(dictentry.FieldDictTypeID, field.TypeUint32, value)
	}
	if _u.mutation.DictTypeIDCleared() {
		_spec.ClearField(dictentry.FieldDictTypeID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(dictentry.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(dictentry.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dictentry.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(dictentry.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(dictentry.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(dictentry.FieldValue, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DictEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
