// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/dicttype"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictTypeCreate is the builder for creating a DictType entity.
type DictTypeCreate struct {
	config
	mutation *DictTypeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DictTypeCreate) SetCreatedAt(v time.Time) *DictTypeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableCreatedAt(v *time.Time) *DictTypeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DictTypeCreate) SetUpdatedAt(v time.Time) *DictTypeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableUpdatedAt(v *time.Time) *DictTypeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DictTypeCreate) SetDeletedAt(v time.Time) *DictTypeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableDeletedAt(v *time.Time) *DictTypeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DictTypeCreate) SetCreatedBy(v uint32) *DictTypeCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableCreatedBy(v *uint32) *DictTypeCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DictTypeCreate) SetUpdatedBy(v uint32) *DictTypeCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableUpdatedBy(v *uint32) *DictTypeCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *DictTypeCreate) SetDeletedBy(v uint32) *DictTypeCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableDeletedBy(v *uint32) *DictTypeCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *DictTypeCreate) SetRemark(v string) *DictTypeCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableRemark(v *string) *DictTypeCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *DictTypeCreate) SetCode(v string) *DictTypeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableCode(v *string) *DictTypeCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DictTypeCreate) SetName(v string) *DictTypeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DictTypeCreate) SetNillableName(v *string) *DictTypeCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DictTypeCreate) SetID(v uint32) *DictTypeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DictTypeMutation object of the builder.
func (_c *DictTypeCreate) Mutation() *DictTypeMutation {
	return _c.mutation
}

// Save creates the DictType in the database.
func (_c *DictTypeCreate) Save(ctx context.Context) (*DictType, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictTypeCreate) SaveX(ctx context.Context) *DictType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictTypeCreate) check() error {
	if v, ok := _c.mutation.Code(); ok {
		if err := dicttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DictType.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := dicttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictType.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := dicttype.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DictType.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DictTypeCreate) sqlSave(ctx context.Context) (*DictType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictTypeCreate) createSpec() (*DictType, *sqlgraph.CreateSpec) {
	var (
		_node = &DictType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dicttype.Table, sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dicttype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dicttype.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(dicttype.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(dicttype.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(dicttype.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(dicttype.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(dicttype.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(dicttype.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dicttype.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DictType.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DictTypeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DictTypeCreate) OnConflict(opts ...sql.ConflictOption) *DictTypeUpsertOne {
	_c.conflict = opts
	return &DictTypeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DictType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DictTypeCreate) OnConflictColumns(columns ...string) *DictTypeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DictTypeUpsertOne{
		create: _c,
	}
}

type (
	// DictTypeUpsertOne is the builder for "upsert"-ing
	//  one DictType node.
	DictTypeUpsertOne struct {
		create *DictTypeCreate
	}

	// DictTypeUpsert is the "OnConflict" setter.
	DictTypeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DictTypeUpsert) SetUpdatedAt(v time.Time) *DictTypeUpsert {
	u.Set(dicttype.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateUpdatedAt() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *DictTypeUpsert) ClearUpdatedAt() *DictTypeUpsert {
	u.SetNull(dicttype.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DictTypeUpsert) SetDeletedAt(v time.Time) *DictTypeUpsert {
	u.Set(dicttype.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateDeletedAt() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DictTypeUpsert) ClearDeletedAt() *DictTypeUpsert {
	u.SetNull(dicttype.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *DictTypeUpsert) SetCreatedBy(v uint32) *DictTypeUpsert {
	u.Set(dicttype.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateCreatedBy() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DictTypeUpsert) AddCreatedBy(v uint32) *DictTypeUpsert {
	u.Add(dicttype.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DictTypeUpsert) ClearCreatedBy() *DictTypeUpsert {
	u.SetNull(dicttype.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *DictTypeUpsert) SetUpdatedBy(v uint32) *DictTypeUpsert {
	u.Set(dicttype.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateUpdatedBy() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *DictTypeUpsert) AddUpdatedBy(v uint32) *DictTypeUpsert {
	u.Add(dicttype.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *DictTypeUpsert) ClearUpdatedBy() *DictTypeUpsert {
	u.SetNull(dicttype.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *DictTypeUpsert) SetDeletedBy(v uint32) *DictTypeUpsert {
	u.Set(dicttype.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateDeletedBy() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *DictTypeUpsert) AddDeletedBy(v uint32) *DictTypeUpsert {
	u.Add(dicttype.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *DictTypeUpsert) ClearDeletedBy() *DictTypeUpsert {
	u.SetNull(dicttype.FieldDeletedBy)
	return u
}

// SetRemark sets the "remark" field.
func (u *DictTypeUpsert) SetRemark(v string) *DictTypeUpsert {
	u.Set(dicttype.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateRemark() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *DictTypeUpsert) ClearRemark() *DictTypeUpsert {
	u.SetNull(dicttype.FieldRemark)
	return u
}

// SetCode sets the "code" field.
func (u *DictTypeUpsert) SetCode(v string) *DictTypeUpsert {
	u.Set(dicttype.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateCode() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *DictTypeUpsert) ClearCode() *DictTypeUpsert {
	u.SetNull(dicttype.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *DictTypeUpsert) SetName(v string) *DictTypeUpsert {
	u.Set(dicttype.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DictTypeUpsert) UpdateName() *DictTypeUpsert {
	u.SetExcluded(dicttype.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *DictTypeUpsert) ClearName() *DictTypeUpsert {
	u.SetNull(dicttype.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DictType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dicttype.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DictTypeUpsertOne) UpdateNewValues() *DictTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dicttype.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dicttype.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DictType.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DictTypeUpsertOne) Ignore() *DictTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DictTypeUpsertOne) DoNothing() *DictTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DictTypeCreate.OnConflict
// documentation for more info.
func (u *DictTypeUpsertOne) Update(set func(*DictTypeUpsert)) *DictTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DictTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DictTypeUpsertOne) SetUpdatedAt(v time.Time) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateUpdatedAt() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *DictTypeUpsertOne) ClearUpdatedAt() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DictTypeUpsertOne) SetDeletedAt(v time.Time) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateDeletedAt() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DictTypeUpsertOne) ClearDeletedAt() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DictTypeUpsertOne) SetCreatedBy(v uint32) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DictTypeUpsertOne) AddCreatedBy(v uint32) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateCreatedBy() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DictTypeUpsertOne) ClearCreatedBy() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *DictTypeUpsertOne) SetUpdatedBy(v uint32) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *DictTypeUpsertOne) AddUpdatedBy(v uint32) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateUpdatedBy() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *DictTypeUpsertOne) ClearUpdatedBy() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *DictTypeUpsertOne) SetDeletedBy(v uint32) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *DictTypeUpsertOne) AddDeletedBy(v uint32) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateDeletedBy() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *DictTypeUpsertOne) ClearDeletedBy() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *DictTypeUpsertOne) SetRemark(v string) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateRemark() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *DictTypeUpsertOne) ClearRemark() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearRemark()
	})
}

// SetCode sets the "code" field.
func (u *DictTypeUpsertOne) SetCode(v string) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateCode() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *DictTypeUpsertOne) ClearCode() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearCode()
	})
}

// SetName sets the "name" field.
func (u *DictTypeUpsertOne) SetName(v string) *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DictTypeUpsertOne) UpdateName() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *DictTypeUpsertOne) ClearName() *DictTypeUpsertOne {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearName()
	})
}

// Exec executes the query.
func (u *DictTypeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DictTypeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DictTypeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DictTypeUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DictTypeUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DictTypeCreateBulk is the builder for creating many DictType entities in bulk.
type DictTypeCreateBulk struct {
	config
	err      error
	builders []*DictTypeCreate
	conflict []sql.ConflictOption
}

// Save creates the DictType entities in the database.
func (_c *DictTypeCreateBulk) Save(ctx context.Context) ([]*DictType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DictType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictTypeCreateBulk) SaveX(ctx context.Context) []*DictType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DictType.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DictTypeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DictTypeCreateBulk) OnConflict(opts ...sql.ConflictOption) *DictTypeUpsertBulk {
	_c.conflict = opts
	return &DictTypeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DictType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DictTypeCreateBulk) OnConflictColumns(columns ...string) *DictTypeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DictTypeUpsertBulk{
		create: _c,
	}
}

// DictTypeUpsertBulk is the builder for "upsert"-ing
// a bulk of DictType nodes.
type DictTypeUpsertBulk struct {
	create *DictTypeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DictType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dicttype.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DictTypeUpsertBulk) UpdateNewValues() *DictTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dicttype.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dicttype.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DictType.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DictTypeUpsertBulk) Ignore() *DictTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DictTypeUpsertBulk) DoNothing() *DictTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DictTypeCreateBulk.OnConflict
// documentation for more info.
func (u *DictTypeUpsertBulk) Update(set func(*DictTypeUpsert)) *DictTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DictTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DictTypeUpsertBulk) SetUpdatedAt(v time.Time) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateUpdatedAt() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *DictTypeUpsertBulk) ClearUpdatedAt() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DictTypeUpsertBulk) SetDeletedAt(v time.Time) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateDeletedAt() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DictTypeUpsertBulk) ClearDeletedAt() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DictTypeUpsertBulk) SetCreatedBy(v uint32) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DictTypeUpsertBulk) AddCreatedBy(v uint32) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateCreatedBy() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DictTypeUpsertBulk) ClearCreatedBy() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *DictTypeUpsertBulk) SetUpdatedBy(v uint32) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *DictTypeUpsertBulk) AddUpdatedBy(v uint32) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateUpdatedBy() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *DictTypeUpsertBulk) ClearUpdatedBy() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *DictTypeUpsertBulk) SetDeletedBy(v uint32) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *DictTypeUpsertBulk) AddDeletedBy(v uint32) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateDeletedBy() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *DictTypeUpsertBulk) ClearDeletedBy() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *DictTypeUpsertBulk) SetRemark(v string) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateRemark() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *DictTypeUpsertBulk) ClearRemark() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearRemark()
	})
}

// SetCode sets the "code" field.
func (u *DictTypeUpsertBulk) SetCode(v string) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateCode() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *DictTypeUpsertBulk) ClearCode() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearCode()
	})
}

// SetName sets the "name" field.
func (u *DictTypeUpsertBulk) SetName(v string) *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DictTypeUpsertBulk) UpdateName() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *DictTypeUpsertBulk) ClearName() *DictTypeUpsertBulk {
	return u.Update(func(s *DictTypeUpsert) {
		s.ClearName()
	})
}

// Exec executes the query.
func (u *DictTypeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DictTypeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DictTypeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DictTypeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
