// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-cms/app/core/service/internal/data/ent/rolemetadata"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 角色元数据表
type RoleMetadata struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 角色ID
	RoleID *uint32 `json:"role_id,omitempty"`
	// TemplateFor holds the value of the "template_for" field.
	TemplateFor *string `json:"template_for,omitempty"`
	// TemplateVersion holds the value of the "template_version" field.
	TemplateVersion *int32 `json:"template_version,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// LastSyncedVersion holds the value of the "last_synced_version" field.
	LastSyncedVersion *int32 `json:"last_synced_version,omitempty"`
	// IsTemplate holds the value of the "is_template" field.
	IsTemplate *bool `json:"is_template,omitempty"`
	// 键
	Key *string `json:"key,omitempty"`
	// 值
	Value        *string `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoleMetadata) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolemetadata.FieldIsTemplate:
			values[i] = new(sql.NullBool)
		case rolemetadata.FieldID, rolemetadata.FieldTenantID, rolemetadata.FieldRoleID, rolemetadata.FieldTemplateVersion, rolemetadata.FieldLastSyncedVersion:
			values[i] = new(sql.NullInt64)
		case rolemetadata.FieldTemplateFor, rolemetadata.FieldKey, rolemetadata.FieldValue:
			values[i] = new(sql.NullString)
		case rolemetadata.FieldCreatedAt, rolemetadata.FieldUpdatedAt, rolemetadata.FieldDeletedAt, rolemetadata.FieldLastSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoleMetadata fields.
func (_m *RoleMetadata) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolemetadata.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case rolemetadata.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case rolemetadata.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case rolemetadata.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case rolemetadata.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case rolemetadata.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = new(uint32)
				*_m.RoleID = uint32(value.Int64)
			}
		case rolemetadata.FieldTemplateFor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_for", values[i])
			} else if value.Valid {
				_m.TemplateFor = new(string)
				*_m.TemplateFor = value.String
			}
		case rolemetadata.FieldTemplateVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_version", values[i])
			} else if value.Valid {
				_m.TemplateVersion = new(int32)
				*_m.TemplateVersion = int32(value.Int64)
			}
		case rolemetadata.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case rolemetadata.FieldLastSyncedVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_version", values[i])
			} else if value.Valid {
				_m.LastSyncedVersion = new(int32)
				*_m.LastSyncedVersion = int32(value.Int64)
			}
		case rolemetadata.FieldIsTemplate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_template", values[i])
			} else if value.Valid {
				_m.IsTemplate = new(bool)
				*_m.IsTemplate = value.Bool
			}
		case rolemetadata.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = new(string)
				*_m.Key = value.String
			}
		case rolemetadata.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = new(string)
				*_m.Value = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the RoleMetadata.
// This includes values selected through modifiers, order, etc.
func (_m *RoleMetadata) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RoleMetadata.
// Note that you need to call RoleMetadata.Unwrap() before calling this method if this RoleMetadata
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoleMetadata) Update() *RoleMetadataUpdateOne {
	return NewRoleMetadataClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoleMetadata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoleMetadata) Unwrap() *RoleMetadata {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoleMetadata is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoleMetadata) String() string {
	var builder strings.Builder
	builder.WriteString("RoleMetadata(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RoleID; v != nil {
		builder.WriteString("role_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TemplateFor; v != nil {
		builder.WriteString("template_for=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TemplateVersion; v != nil {
		builder.WriteString("template_version=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSyncedVersion; v != nil {
		builder.WriteString("last_synced_version=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsTemplate; v != nil {
		builder.WriteString("is_template=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Key; v != nil {
		builder.WriteString("key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Value; v != nil {
		builder.WriteString("value=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// RoleMetadataSlice is a parsable slice of RoleMetadata.
type RoleMetadataSlice []*RoleMetadata
