// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-ledger/app/core/service/internal/data/ent/usercredential"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 用户凭证表
type UserCredential struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 用户ID
	UserID *uint32 `json:"user_id,omitempty"`
	// Identifier holds the value of the "identifier" field.
	Identifier *string `json:"identifier,omitempty"`
	// IdentityType holds the value of the "identity_type" field.
	IdentityType *string `json:"identity_type,omitempty"`
	// 凭证类型
	CredentialType *string `json:"credential_type,omitempty"`
	// 凭证值
	Credential *string `json:"credential,omitempty"`
	// ProviderAccountID holds the value of the "provider_account_id" field.
	ProviderAccountID *string `json:"provider_account_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider *string `json:"provider,omitempty"`
	// ExtraInfo holds the value of the "extra_info" field.
	ExtraInfo *string `json:"extra_info,omitempty"`
	// IsPrimary holds the value of the "is_primary" field.
	IsPrimary *bool `json:"is_primary,omitempty"`
	// Status holds the value of the "status" field.
	Status *usercredential.Status `json:"status,omitempty"`
	// 已验证
	Verified     *bool `json:"verified,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercredential.FieldIsPrimary, usercredential.FieldVerified:
			values[i] = new(sql.NullBool)
		case usercredential.FieldID, usercredential.FieldTenantID, usercredential.FieldCreatedBy, usercredential.FieldUpdatedBy, usercredential.FieldDeletedBy, usercredential.FieldUserID:
			values[i] = new(sql.NullInt64)
		case usercredential.FieldIdentifier, usercredential.FieldIdentityType, usercredential.FieldCredentialType, usercredential.FieldCredential, usercredential.FieldProviderAccountID, usercredential.FieldProvider, usercredential.FieldExtraInfo, usercredential.FieldStatus:
			values[i] = new(sql.NullString)
		case usercredential.FieldCreatedAt, usercredential.FieldUpdatedAt, usercredential.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCredential fields.
func (_m *UserCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case usercredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case usercredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case usercredential.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case usercredential.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case usercredential.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case usercredential.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case usercredential.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case usercredential.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uint32)
				*_m.UserID = uint32(value.Int64)
			}
		case usercredential.FieldIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identifier", values[i])
			} else if value.Valid {
				_m.Identifier = new(string)
				*_m.Identifier = value.String
			}
		case usercredential.FieldIdentityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_type", values[i])
			} else if value.Valid {
				_m.IdentityType = new(string)
				*_m.IdentityType = value.String
			}
		case usercredential.FieldCredentialType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_type", values[i])
			} else if value.Valid {
				_m.CredentialType = new(string)
				*_m.CredentialType = value.String
			}
		case usercredential.FieldCredential:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential", values[i])
			} else if value.Valid {
				_m.Credential = new(string)
				*_m.Credential = value.String
			}
		case usercredential.FieldProviderAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_account_id", values[i])
			} else if value.Valid {
				_m.ProviderAccountID = new(string)
				*_m.ProviderAccountID = value.String
			}
		case usercredential.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = new(string)
				*_m.Provider = value.String
			}
		case usercredential.FieldExtraInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra_info", values[i])
			} else if value.Valid {
				_m.ExtraInfo = new(string)
				*_m.ExtraInfo = value.String
			}
		case usercredential.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				_m.IsPrimary = new(bool)
				*_m.IsPrimary = value.Bool
			}
		case usercredential.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(usercredential.Status)
				*_m.Status = usercredential.Status(value.String)
			}
		case usercredential.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				_m.Verified = new(bool)
				*_m.Verified = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCredential.
// This includes values selected through modifiers, order, etc.
func (_m *UserCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserCredential.
// Note that you need to call UserCredential.Unwrap() before calling this method if this UserCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCredential) Update() *UserCredentialUpdateOne {
	return NewUserCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCredential) Unwrap() *UserCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCredential) String() string {
	var builder strings.Builder
	builder.WriteString("UserCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Identifier; v != nil {
		builder.WriteString("identifier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdentityType; v != nil {
		builder.WriteString("identity_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CredentialType; v != nil {
		builder.WriteString("credential_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Credential; v != nil {
		builder.WriteString("credential=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderAccountID; v != nil {
		builder.WriteString("provider_account_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Provider; v != nil {
		builder.WriteString("provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExtraInfo; v != nil {
		builder.WriteString("extra_info=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IsPrimary; v != nil {
		builder.WriteString("is_primary=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Verified; v != nil {
		builder.WriteString("verified=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserCredentials is a parsable slice of UserCredential.
type UserCredentials []*UserCredential
