syntax = "proto3";

package ledger.service.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";
import "pagination/v1/pagination.proto";

// 标签服务
service TagService {
  rpc List (pagination.PagingRequest) returns (ListTagResponse) {}
  rpc ListAll (ListAllTagRequest) returns (ListTagResponse) {}
  rpc Get (GetTagRequest) returns (Tag) {}
  rpc Create (CreateTagRequest) returns (Tag) {}
  rpc Update (UpdateTagRequest) returns (Tag) {}
  rpc Delete (DeleteTagRequest) returns (google.protobuf.Empty) {}
  rpc Toggle (ToggleTagRequest) returns (Tag) {}
  rpc ToggleCanExpense (ToggleTagRequest) returns (Tag) {}
  rpc ToggleCanIncome (ToggleTagRequest) returns (Tag) {}
  rpc ToggleCanTransfer (ToggleTagRequest) returns (Tag) {}
}

message Tag {
  optional uint32 id = 1 [json_name = "id"];
  optional uint32 tenant_id = 2 [json_name = "tenantId"];
  optional uint32 book_id = 3 [json_name = "bookId"];

  optional string name = 10 [json_name = "name"];
  optional string notes = 11 [json_name = "notes"];
  optional bool enable = 12 [json_name = "enable"];

  optional bool can_expense = 13 [
    json_name = "canExpense",
    (gnostic.openapi.v3.property) = {description: "是否可用于支出"}
  ];
  optional bool can_income = 14 [
    json_name = "canIncome",
    (gnostic.openapi.v3.property) = {description: "是否可用于收入"}
  ];
  optional bool can_transfer = 15 [
    json_name = "canTransfer",
    (gnostic.openapi.v3.property) = {description: "是否可用于转账"}
  ];

  optional int32 sort_order = 16 [json_name = "sortOrder"];

  // 树形字段
  optional uint32 parent_id = 60 [json_name = "parentId"];
  repeated Tag children = 61 [json_name = "children"];
  optional int32 depth = 62 [json_name = "depth"];
  optional string path = 63 [json_name = "path"];

  optional uint32 created_by = 100 [json_name = "createdBy"];
  optional uint32 updated_by = 101 [json_name = "updatedBy"];
  optional uint32 deleted_by = 102 [json_name = "deletedBy"];

  optional google.protobuf.Timestamp created_at = 200 [json_name = "createdAt"];
  optional google.protobuf.Timestamp updated_at = 201 [json_name = "updatedAt"];
  optional google.protobuf.Timestamp deleted_at = 202 [json_name = "deletedAt"];
}

message ListTagResponse {
  repeated Tag items = 1;
  uint64 total = 2;
}

message ListAllTagRequest {
  optional uint32 book_id = 1 [json_name = "bookId"];
}

message GetTagRequest {
  uint32 id = 1 [json_name = "id"];
  optional google.protobuf.FieldMask view_mask = 100 [json_name = "viewMask"];
}

message CreateTagRequest {
  Tag data = 1;
}

message UpdateTagRequest {
  uint32 id = 1;
  Tag data = 2;
  google.protobuf.FieldMask update_mask = 3 [json_name = "updateMask"];
  optional bool allow_missing = 4 [json_name = "allowMissing"];
}

message DeleteTagRequest {
  uint32 id = 1 [json_name = "id"];
}

message ToggleTagRequest {
  uint32 id = 1 [json_name = "id"];
}
