syntax = "proto3";
package app.service.v1;
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "pagination/v1/pagination.proto";
import "ledger/service/v1/account.proto";

service AccountService {
  rpc List (pagination.PagingRequest) returns (ledger.service.v1.ListAccountResponse) {
    option (google.api.http) = { get: "/app/v1/accounts" };
  }
  rpc ListAll (ledger.service.v1.ListAllAccountRequest) returns (ledger.service.v1.ListAccountResponse) {
    option (google.api.http) = { get: "/app/v1/accounts/all" };
  }
  rpc Get (ledger.service.v1.GetAccountRequest) returns (ledger.service.v1.Account) {
    option (google.api.http) = { get: "/app/v1/accounts/{id}" };
  }
  rpc Create (ledger.service.v1.CreateAccountRequest) returns (ledger.service.v1.Account) {
    option (google.api.http) = { post: "/app/v1/accounts" body: "*" };
  }
  rpc Update (ledger.service.v1.UpdateAccountRequest) returns (ledger.service.v1.Account) {
    option (google.api.http) = { put: "/app/v1/accounts/{id}" body: "*" };
  }
  rpc Delete (ledger.service.v1.DeleteAccountRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = { delete: "/app/v1/accounts/{id}" };
  }
  rpc Toggle (ledger.service.v1.ToggleAccountRequest) returns (ledger.service.v1.Account) {
    option (google.api.http) = { patch: "/app/v1/accounts/{id}/toggle" body: "*" };
  }
  rpc AdjustBalance (ledger.service.v1.AdjustBalanceRequest) returns (ledger.service.v1.Account) {
    option (google.api.http) = { post: "/app/v1/accounts/{id}/adjust" body: "*" };
  }
  rpc Overview (ledger.service.v1.OverviewRequest) returns (ledger.service.v1.OverviewResponse) {
    option (google.api.http) = { get: "/app/v1/account-overview" };
  }
  rpc Statistics (ledger.service.v1.AccountStatisticsRequest) returns (ledger.service.v1.AccountStatisticsResponse) {
    option (google.api.http) = { get: "/app/v1/account-statistics" };
  }
}
