syntax = "proto3";
package app.service.v1;
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "pagination/v1/pagination.proto";
import "ledger/service/v1/balance_flow.proto";

service BalanceFlowService {
  rpc List (pagination.PagingRequest) returns (ledger.service.v1.ListBalanceFlowResponse) {
    option (google.api.http) = { get: "/app/v1/balance-flows" };
  }
  rpc Get (ledger.service.v1.GetBalanceFlowRequest) returns (ledger.service.v1.BalanceFlow) {
    option (google.api.http) = { get: "/app/v1/balance-flows/{id}" };
  }
  rpc Create (ledger.service.v1.CreateBalanceFlowRequest) returns (ledger.service.v1.BalanceFlow) {
    option (google.api.http) = { post: "/app/v1/balance-flows" body: "*" };
  }
  rpc Update (ledger.service.v1.UpdateBalanceFlowRequest) returns (ledger.service.v1.BalanceFlow) {
    option (google.api.http) = { put: "/app/v1/balance-flows/{id}" body: "*" };
  }
  rpc Delete (ledger.service.v1.DeleteBalanceFlowRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = { delete: "/app/v1/balance-flows/{id}" };
  }
  rpc Confirm (ledger.service.v1.ConfirmBalanceFlowRequest) returns (ledger.service.v1.BalanceFlow) {
    option (google.api.http) = { patch: "/app/v1/balance-flows/{id}/confirm" body: "*" };
  }
  rpc Statistics (ledger.service.v1.StatisticsRequest) returns (ledger.service.v1.StatisticsResponse) {
    option (google.api.http) = { get: "/app/v1/balance-flows/statistics" };
  }
}
