syntax = "proto3";

package app.service.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

import "ledger/service/v1/flow_file.proto";

service FlowFileService {
  rpc List (ledger.service.v1.ListFlowFileRequest) returns (ledger.service.v1.ListFlowFileResponse) {
    option (google.api.http) = {
      get: "/app/v1/flow-files"
    };
  }

  rpc Delete (ledger.service.v1.DeleteFlowFileRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/app/v1/flow-files/{id}"
    };
  }

  rpc UploadFile (ledger.service.v1.UploadFlowFileRequest) returns (ledger.service.v1.FlowFile) {
    option (google.api.http) = {
      post: "/app/v1/flow-files-upload"
      body: "*"
    };
  }

  rpc ViewFile (ledger.service.v1.ViewFlowFileRequest) returns (ledger.service.v1.ViewFlowFileResponse) {
    option (google.api.http) = {
      get: "/app/v1/flow-files-view"
    };
  }
}
