// Code generated by ent, DO NOT EDIT.

package categoryrelation

import (
	"go-wind-cms/app/core/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLTE(FieldID, id))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldCategoryID, v))
}

// BalanceFlowID applies equality check predicate on the "balance_flow_id" field. It's identical to BalanceFlowIDEQ.
func BalanceFlowID(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldBalanceFlowID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldAmount, v))
}

// ConvertedAmount applies equality check predicate on the "converted_amount" field. It's identical to ConvertedAmountEQ.
func ConvertedAmount(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldConvertedAmount, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDGT applies the GT predicate on the "category_id" field.
func CategoryIDGT(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGT(FieldCategoryID, v))
}

// CategoryIDGTE applies the GTE predicate on the "category_id" field.
func CategoryIDGTE(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGTE(FieldCategoryID, v))
}

// CategoryIDLT applies the LT predicate on the "category_id" field.
func CategoryIDLT(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLT(FieldCategoryID, v))
}

// CategoryIDLTE applies the LTE predicate on the "category_id" field.
func CategoryIDLTE(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLTE(FieldCategoryID, v))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotNull(FieldCategoryID))
}

// BalanceFlowIDEQ applies the EQ predicate on the "balance_flow_id" field.
func BalanceFlowIDEQ(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldBalanceFlowID, v))
}

// BalanceFlowIDNEQ applies the NEQ predicate on the "balance_flow_id" field.
func BalanceFlowIDNEQ(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNEQ(FieldBalanceFlowID, v))
}

// BalanceFlowIDIn applies the In predicate on the "balance_flow_id" field.
func BalanceFlowIDIn(vs ...uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIn(FieldBalanceFlowID, vs...))
}

// BalanceFlowIDNotIn applies the NotIn predicate on the "balance_flow_id" field.
func BalanceFlowIDNotIn(vs ...uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotIn(FieldBalanceFlowID, vs...))
}

// BalanceFlowIDGT applies the GT predicate on the "balance_flow_id" field.
func BalanceFlowIDGT(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGT(FieldBalanceFlowID, v))
}

// BalanceFlowIDGTE applies the GTE predicate on the "balance_flow_id" field.
func BalanceFlowIDGTE(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGTE(FieldBalanceFlowID, v))
}

// BalanceFlowIDLT applies the LT predicate on the "balance_flow_id" field.
func BalanceFlowIDLT(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLT(FieldBalanceFlowID, v))
}

// BalanceFlowIDLTE applies the LTE predicate on the "balance_flow_id" field.
func BalanceFlowIDLTE(v uint32) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLTE(FieldBalanceFlowID, v))
}

// BalanceFlowIDIsNil applies the IsNil predicate on the "balance_flow_id" field.
func BalanceFlowIDIsNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIsNull(FieldBalanceFlowID))
}

// BalanceFlowIDNotNil applies the NotNil predicate on the "balance_flow_id" field.
func BalanceFlowIDNotNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotNull(FieldBalanceFlowID))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLTE(FieldAmount, v))
}

// AmountIsNil applies the IsNil predicate on the "amount" field.
func AmountIsNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIsNull(FieldAmount))
}

// AmountNotNil applies the NotNil predicate on the "amount" field.
func AmountNotNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotNull(FieldAmount))
}

// ConvertedAmountEQ applies the EQ predicate on the "converted_amount" field.
func ConvertedAmountEQ(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldEQ(FieldConvertedAmount, v))
}

// ConvertedAmountNEQ applies the NEQ predicate on the "converted_amount" field.
func ConvertedAmountNEQ(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNEQ(FieldConvertedAmount, v))
}

// ConvertedAmountIn applies the In predicate on the "converted_amount" field.
func ConvertedAmountIn(vs ...float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIn(FieldConvertedAmount, vs...))
}

// ConvertedAmountNotIn applies the NotIn predicate on the "converted_amount" field.
func ConvertedAmountNotIn(vs ...float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotIn(FieldConvertedAmount, vs...))
}

// ConvertedAmountGT applies the GT predicate on the "converted_amount" field.
func ConvertedAmountGT(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGT(FieldConvertedAmount, v))
}

// ConvertedAmountGTE applies the GTE predicate on the "converted_amount" field.
func ConvertedAmountGTE(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldGTE(FieldConvertedAmount, v))
}

// ConvertedAmountLT applies the LT predicate on the "converted_amount" field.
func ConvertedAmountLT(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLT(FieldConvertedAmount, v))
}

// ConvertedAmountLTE applies the LTE predicate on the "converted_amount" field.
func ConvertedAmountLTE(v float64) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldLTE(FieldConvertedAmount, v))
}

// ConvertedAmountIsNil applies the IsNil predicate on the "converted_amount" field.
func ConvertedAmountIsNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldIsNull(FieldConvertedAmount))
}

// ConvertedAmountNotNil applies the NotNil predicate on the "converted_amount" field.
func ConvertedAmountNotNil() predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.FieldNotNull(FieldConvertedAmount))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CategoryRelation) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CategoryRelation) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CategoryRelation) predicate.CategoryRelation {
	return predicate.CategoryRelation(sql.NotPredicates(p))
}
