syntax = "proto3";

package admin.service.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "pagination/v1/pagination.proto";

import "ledger/service/v1/book.proto";

// 账本服务（Admin BFF）
service BookService {
  rpc List (pagination.PagingRequest) returns (ledger.service.v1.ListBookResponse) {
    option (google.api.http) = {
      get: "/admin/v1/books"
    };
  }

  rpc ListAll (ledger.service.v1.ListAllBookRequest) returns (ledger.service.v1.ListBookResponse) {
    option (google.api.http) = {
      get: "/admin/v1/books-all"
    };
  }

  rpc Get (ledger.service.v1.GetBookRequest) returns (ledger.service.v1.Book) {
    option (google.api.http) = {
      get: "/admin/v1/books/{id}"
    };
  }

  rpc Create (ledger.service.v1.CreateBookRequest) returns (ledger.service.v1.Book) {
    option (google.api.http) = {
      post: "/admin/v1/books"
      body: "*"
    };
  }

  rpc Update (ledger.service.v1.UpdateBookRequest) returns (ledger.service.v1.Book) {
    option (google.api.http) = {
      put: "/admin/v1/books/{id}"
      body: "*"
    };
  }

  rpc Delete (ledger.service.v1.DeleteBookRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/admin/v1/books/{id}"
    };
  }

  rpc Toggle (ledger.service.v1.ToggleBookRequest) returns (ledger.service.v1.Book) {
    option (google.api.http) = {
      patch: "/admin/v1/books/{id}/toggle"
      body: "*"
    };
  }

  rpc CreateByTemplate (ledger.service.v1.CreateBookByTemplateRequest) returns (ledger.service.v1.Book) {
    option (google.api.http) = {
      post: "/admin/v1/books-from-template"
      body: "*"
    };
  }

  rpc Copy (ledger.service.v1.CopyBookRequest) returns (ledger.service.v1.Book) {
    option (google.api.http) = {
      post: "/admin/v1/books-copy"
      body: "*"
    };
  }

  rpc Export (ledger.service.v1.ExportBookRequest) returns (ledger.service.v1.ExportBookResponse) {
    option (google.api.http) = {
      get: "/admin/v1/books/{id}/export"
    };
  }

  rpc ListAllBooks (google.protobuf.Empty) returns (ledger.service.v1.ListBookResponse) {
    option (google.api.http) = {
      get: "/admin/v1/books-select-all"
    };
  }
}
