syntax = "proto3";

package admin.service.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "pagination/v1/pagination.proto";

import "ledger/service/v1/tag.proto";

// 记账标签服务（Admin BFF）
service LedgerTagService {
  rpc List (pagination.PagingRequest) returns (ledger.service.v1.ListTagResponse) {
    option (google.api.http) = {
      get: "/admin/v1/ledger-tags"
    };
  }

  rpc ListAll (ledger.service.v1.ListAllTagRequest) returns (ledger.service.v1.ListTagResponse) {
    option (google.api.http) = {
      get: "/admin/v1/ledger-tags-all"
    };
  }

  rpc Get (ledger.service.v1.GetTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      get: "/admin/v1/ledger-tags/{id}"
    };
  }

  rpc Create (ledger.service.v1.CreateTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      post: "/admin/v1/ledger-tags"
      body: "*"
    };
  }

  rpc Update (ledger.service.v1.UpdateTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      put: "/admin/v1/ledger-tags/{id}"
      body: "*"
    };
  }

  rpc Delete (ledger.service.v1.DeleteTagRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/admin/v1/ledger-tags/{id}"
    };
  }

  rpc Toggle (ledger.service.v1.ToggleTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      patch: "/admin/v1/ledger-tags/{id}/toggle"
      body: "*"
    };
  }

  rpc ToggleCanExpense (ledger.service.v1.ToggleTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      patch: "/admin/v1/ledger-tags/{id}/toggle-can-expense"
      body: "*"
    };
  }

  rpc ToggleCanIncome (ledger.service.v1.ToggleTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      patch: "/admin/v1/ledger-tags/{id}/toggle-can-income"
      body: "*"
    };
  }

  rpc ToggleCanTransfer (ledger.service.v1.ToggleTagRequest) returns (ledger.service.v1.Tag) {
    option (google.api.http) = {
      patch: "/admin/v1/ledger-tags/{id}/toggle-can-transfer"
      body: "*"
    };
  }
}
