// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-cms/app/core/service/internal/data"
	"go-wind-cms/app/core/service/internal/server"
	"go-wind-cms/app/core/service/internal/service"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/registry/etcd"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v := server.NewGrpcMiddleware(context)
	authenticatorOption := data.NewAuthenticatorConfig(context)
	client, cleanup, err := data.NewRedisClient(context)
	if err != nil {
		return nil, nil, err
	}
	userTokenCache := data.NewUserTokenCache(context, client)
	authenticator := data.NewAuthenticator(context, authenticatorOption, userTokenCache)
	entClient, cleanup2, err := data.NewEntClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userCredentialRepo := data.NewUserCredentialRepo(context, entClient)
	userRoleRepo := data.NewUserRoleRepo(context, entClient)
	userOrgUnitRepo := data.NewUserOrgUnitRepo(context, entClient)
	userPositionRepo := data.NewUserPositionRepo(context, entClient)
	membershipRepo := data.NewMembershipRepo(context, entClient)
	userRepo := data.NewUserRepo(context, entClient, userRoleRepo, userOrgUnitRepo, userPositionRepo, membershipRepo)
	roleRepo := data.NewRoleRepo(context, entClient)
	tenantRepo := data.NewTenantRepo(context, entClient)
	permissionRepo := data.NewPermissionRepo(context, entClient)
	authenticationService := service.NewAuthenticationService(context, authenticator, userCredentialRepo, userRepo, roleRepo, tenantRepo, permissionRepo)
	loginPolicyRepo := data.NewLoginPolicyRepo(context, entClient)
	loginPolicyService := service.NewLoginPolicyService(context, loginPolicyRepo)
	userCredentialService := service.NewUserCredentialService(context, userCredentialRepo)
	taskRepo := data.NewTaskRepo(context, entClient)
	taskService := service.NewTaskService(context, taskRepo, userRepo)
	fileRepo := data.NewFileRepo(context, entClient)
	minIOClient := data.NewMinIoClient(context)
	fileService := service.NewFileService(context, fileRepo, minIOClient)
	languageRepo := data.NewLanguageRepo(context, entClient)
	languageService := service.NewLanguageService(context, languageRepo)
	tenantService := service.NewTenantService(context, tenantRepo, userRepo, userCredentialRepo, roleRepo)
	positionRepo := data.NewPositionRepo(context, entClient)
	orgUnitRepo := data.NewOrgUnitRepo(context, entClient)
	userService := service.NewUserService(context, userRepo, roleRepo, userCredentialRepo, positionRepo, orgUnitRepo, tenantRepo, membershipRepo)
	roleService := service.NewRoleService(context, roleRepo)
	positionService := service.NewPositionService(context, positionRepo)
	orgUnitService := service.NewOrgUnitService(context, orgUnitRepo)
	menuRepo := data.NewMenuRepo(context, entClient)
	menuService := service.NewMenuService(context, menuRepo)
	apiRepo := data.NewApiRepo(context, entClient)
	apiService := service.NewApiService(context, apiRepo)
	permissionGroupRepo := data.NewPermissionGroupRepo(context, entClient)
	permissionService := service.NewPermissionService(context, permissionRepo, permissionGroupRepo, menuRepo, apiRepo, roleRepo)
	permissionGroupService := service.NewPermissionGroupService(context, permissionGroupRepo, permissionRepo)
	permissionAuditLogRepo := data.NewPermissionAuditLogRepo(context, entClient)
	permissionAuditLogService := service.NewPermissionAuditLogService(context, permissionAuditLogRepo)
	policyEvaluationLogRepo := data.NewPolicyEvaluationLogRepo(context, entClient)
	policyEvaluationLogService := service.NewPolicyEvaluationLogService(context, policyEvaluationLogRepo)
	loginAuditLogRepo := data.NewLoginAuditLogRepo(context, entClient)
	loginAuditLogService := service.NewLoginAuditLogService(context, loginAuditLogRepo)
	apiAuditLogRepo := data.NewApiAuditLogRepo(context, entClient)
	apiAuditLogService := service.NewApiAuditLogService(context, apiAuditLogRepo)
	operationAuditLogRepo := data.NewOperationAuditLogRepo(context, entClient)
	operationAuditLogService := service.NewOperationAuditLogService(context, operationAuditLogRepo)
	dataAccessAuditLogRepo := data.NewDataAccessAuditLogRepo(context, entClient)
	dataAccessAuditLogService := service.NewDataAccessAuditLogService(context, dataAccessAuditLogRepo)
	bookRepo := data.NewBookRepo(context, entClient)
	bookService := service.NewBookService(context, bookRepo)
	accountRepo := data.NewAccountRepo(context, entClient)
	balanceFlowRepo := data.NewBalanceFlowRepo(context, entClient)
	accountService := service.NewAccountService(context, accountRepo, balanceFlowRepo)
	categoryRepo := data.NewCategoryRepo(context, entClient)
	categoryService := service.NewCategoryService(context, categoryRepo)
	tagRepo := data.NewTagRepo(context, entClient)
	tagService := service.NewTagService(context, tagRepo)
	payeeRepo := data.NewPayeeRepo(context, entClient)
	payeeService := service.NewPayeeService(context, payeeRepo)
	flowFileRepo := data.NewFlowFileRepo(context, entClient, minIOClient)
	balanceFlowService := service.NewBalanceFlowService(context, balanceFlowRepo, flowFileRepo)
	noteDayRepo := data.NewNoteDayRepo(context, entClient)
	noteDayService := service.NewNoteDayService(context, noteDayRepo)
	currencyService := service.NewCurrencyService(context)
	reportService := service.NewReportService(context, balanceFlowRepo, accountRepo)
	flowFileService := service.NewFlowFileService(context, flowFileRepo)
	membershipService := service.NewMembershipService(context, membershipRepo, userRepo, tenantRepo, roleRepo)
	budgetRepo := data.NewBudgetRepo(context, entClient)
	budgetService := service.NewBudgetService(context, budgetRepo, balanceFlowRepo)
	ledgerAuthService := service.NewLedgerAuthService(context, entClient, authenticator, userRepo, tenantRepo, bookRepo, membershipRepo)
	grpcServer, err := server.NewGrpcServer(context, v, authenticationService, loginPolicyService, userCredentialService, taskService, fileService, languageService, tenantService, userService, roleService, positionService, orgUnitService, menuService, apiService, permissionService, permissionGroupService, permissionAuditLogService, policyEvaluationLogService, loginAuditLogService, apiAuditLogService, operationAuditLogService, dataAccessAuditLogService, bookService, accountService, categoryService, tagService, payeeService, balanceFlowService, noteDayService, currencyService, reportService, flowFileService, membershipService, budgetService, ledgerAuthService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	asynqServer := server.NewAsynqServer(context, taskService)
	app := newApp(context, grpcServer, asynqServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
