// Code generated by ent, DO NOT EDIT.

package permissionauditlog

import (
	"go-wind-ledger/app/core/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldDeletedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldTenantID, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldOperatorID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldAction, v))
}

// OperatedAt applies equality check predicate on the "operated_at" field. It's identical to OperatedAtEQ.
func OperatedAt(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldOperatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldDeletedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldTenantID))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v uint32) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorIDIsNil applies the IsNil predicate on the "operator_id" field.
func OperatorIDIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldOperatorID))
}

// OperatorIDNotNil applies the NotNil predicate on the "operator_id" field.
func OperatorIDNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldOperatorID))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldHasSuffix(FieldAction, v))
}

// ActionIsNil applies the IsNil predicate on the "action" field.
func ActionIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldAction))
}

// ActionNotNil applies the NotNil predicate on the "action" field.
func ActionNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldAction))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldContainsFold(FieldAction, v))
}

// OperatedAtEQ applies the EQ predicate on the "operated_at" field.
func OperatedAtEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldEQ(FieldOperatedAt, v))
}

// OperatedAtNEQ applies the NEQ predicate on the "operated_at" field.
func OperatedAtNEQ(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNEQ(FieldOperatedAt, v))
}

// OperatedAtIn applies the In predicate on the "operated_at" field.
func OperatedAtIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIn(FieldOperatedAt, vs...))
}

// OperatedAtNotIn applies the NotIn predicate on the "operated_at" field.
func OperatedAtNotIn(vs ...time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotIn(FieldOperatedAt, vs...))
}

// OperatedAtGT applies the GT predicate on the "operated_at" field.
func OperatedAtGT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGT(FieldOperatedAt, v))
}

// OperatedAtGTE applies the GTE predicate on the "operated_at" field.
func OperatedAtGTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldGTE(FieldOperatedAt, v))
}

// OperatedAtLT applies the LT predicate on the "operated_at" field.
func OperatedAtLT(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLT(FieldOperatedAt, v))
}

// OperatedAtLTE applies the LTE predicate on the "operated_at" field.
func OperatedAtLTE(v time.Time) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldLTE(FieldOperatedAt, v))
}

// OperatedAtIsNil applies the IsNil predicate on the "operated_at" field.
func OperatedAtIsNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldIsNull(FieldOperatedAt))
}

// OperatedAtNotNil applies the NotNil predicate on the "operated_at" field.
func OperatedAtNotNil() predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.FieldNotNull(FieldOperatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PermissionAuditLog) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PermissionAuditLog) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PermissionAuditLog) predicate.PermissionAuditLog {
	return predicate.PermissionAuditLog(sql.NotPredicates(p))
}
